// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//  **** IMPORTANT NOTE ****
//
//  The proto of BT data has to match exactly the g3 proto, including tag
//  number.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Triple.
type Triple struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectId     string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Predicate     string                 `protobuf:"bytes,2,opt,name=predicate,proto3" json:"predicate,omitempty"`
	ObjectId      string                 `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	ObjectName    string                 `protobuf:"bytes,4,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"` // Only when object_id is set.
	ObjectValue   string                 `protobuf:"bytes,5,opt,name=object_value,json=objectValue,proto3" json:"object_value,omitempty"`
	ProvenanceId  string                 `protobuf:"bytes,6,opt,name=provenance_id,json=provenanceId,proto3" json:"provenance_id,omitempty"`
	SubjectName   string                 `protobuf:"bytes,7,opt,name=subject_name,json=subjectName,proto3" json:"subject_name,omitempty"`    // Only for in arcs.
	SubjectTypes  []string               `protobuf:"bytes,8,rep,name=subject_types,json=subjectTypes,proto3" json:"subject_types,omitempty"` // Only for in arcs.
	ObjectTypes   []string               `protobuf:"bytes,10,rep,name=object_types,json=objectTypes,proto3" json:"object_types,omitempty"`   // Only when object_id is set.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Triple) Reset() {
	*x = Triple{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Triple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Triple) ProtoMessage() {}

func (x *Triple) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Triple.ProtoReflect.Descriptor instead.
func (*Triple) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *Triple) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *Triple) GetPredicate() string {
	if x != nil {
		return x.Predicate
	}
	return ""
}

func (x *Triple) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *Triple) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *Triple) GetObjectValue() string {
	if x != nil {
		return x.ObjectValue
	}
	return ""
}

func (x *Triple) GetProvenanceId() string {
	if x != nil {
		return x.ProvenanceId
	}
	return ""
}

func (x *Triple) GetSubjectName() string {
	if x != nil {
		return x.SubjectName
	}
	return ""
}

func (x *Triple) GetSubjectTypes() []string {
	if x != nil {
		return x.SubjectTypes
	}
	return nil
}

func (x *Triple) GetObjectTypes() []string {
	if x != nil {
		return x.ObjectTypes
	}
	return nil
}

// A collection of triples.
type Triples struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Triples []*Triple              `protobuf:"bytes,1,rep,name=triples,proto3" json:"triples,omitempty"`
	// Before potential truncation.
	Total float64 `protobuf:"fixed64,6,opt,name=total,proto3" json:"total,omitempty"`
	// A predicate could link to multiple neighbors.
	InNodes       map[string]*EntityInfoCollection `protobuf:"bytes,3,rep,name=in_nodes,json=inNodes,proto3" json:"in_nodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`    // Key is predicate.
	OutNodes      map[string]*EntityInfoCollection `protobuf:"bytes,4,rep,name=out_nodes,json=outNodes,proto3" json:"out_nodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key is predicate.
	SubjectId     string                           `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Triples) Reset() {
	*x = Triples{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Triples) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Triples) ProtoMessage() {}

func (x *Triples) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Triples.ProtoReflect.Descriptor instead.
func (*Triples) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *Triples) GetTriples() []*Triple {
	if x != nil {
		return x.Triples
	}
	return nil
}

func (x *Triples) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Triples) GetInNodes() map[string]*EntityInfoCollection {
	if x != nil {
		return x.InNodes
	}
	return nil
}

func (x *Triples) GetOutNodes() map[string]*EntityInfoCollection {
	if x != nil {
		return x.OutNodes
	}
	return nil
}

func (x *Triples) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

// Full lists of in and out labels for a given node ID.
type PropertyLabels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InLabels      []string               `protobuf:"bytes,1,rep,name=in_labels,json=inLabels,proto3" json:"in_labels,omitempty"`
	OutLabels     []string               `protobuf:"bytes,2,rep,name=out_labels,json=outLabels,proto3" json:"out_labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyLabels) Reset() {
	*x = PropertyLabels{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyLabels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyLabels) ProtoMessage() {}

func (x *PropertyLabels) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyLabels.ProtoReflect.Descriptor instead.
func (*PropertyLabels) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

func (x *PropertyLabels) GetInLabels() []string {
	if x != nil {
		return x.InLabels
	}
	return nil
}

func (x *PropertyLabels) GetOutLabels() []string {
	if x != nil {
		return x.OutLabels
	}
	return nil
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\vdatacommons\x1a\fentity.proto\"\xb6\x02\n" +
	"\x06Triple\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12\x1c\n" +
	"\tpredicate\x18\x02 \x01(\tR\tpredicate\x12\x1b\n" +
	"\tobject_id\x18\x03 \x01(\tR\bobjectId\x12\x1f\n" +
	"\vobject_name\x18\x04 \x01(\tR\n" +
	"objectName\x12!\n" +
	"\fobject_value\x18\x05 \x01(\tR\vobjectValue\x12#\n" +
	"\rprovenance_id\x18\x06 \x01(\tR\fprovenanceId\x12!\n" +
	"\fsubject_name\x18\a \x01(\tR\vsubjectName\x12#\n" +
	"\rsubject_types\x18\b \x03(\tR\fsubjectTypes\x12!\n" +
	"\fobject_types\x18\n" +
	" \x03(\tR\vobjectTypes\"\xb1\x03\n" +
	"\aTriples\x12-\n" +
	"\atriples\x18\x01 \x03(\v2\x13.datacommons.TripleR\atriples\x12\x14\n" +
	"\x05total\x18\x06 \x01(\x01R\x05total\x12<\n" +
	"\bin_nodes\x18\x03 \x03(\v2!.datacommons.Triples.InNodesEntryR\ainNodes\x12?\n" +
	"\tout_nodes\x18\x04 \x03(\v2\".datacommons.Triples.OutNodesEntryR\boutNodes\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tR\tsubjectId\x1a]\n" +
	"\fInNodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.datacommons.EntityInfoCollectionR\x05value:\x028\x01\x1a^\n" +
	"\rOutNodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.datacommons.EntityInfoCollectionR\x05value:\x028\x01J\x04\b\x02\x10\x03\"L\n" +
	"\x0ePropertyLabels\x12\x1b\n" +
	"\tin_labels\x18\x01 \x03(\tR\binLabels\x12\x1d\n" +
	"\n" +
	"out_labels\x18\x02 \x03(\tR\toutLabelsB0Z.github.com/datacommonsorg/mixer/internal/protob\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_node_proto_goTypes = []any{
	(*Triple)(nil),               // 0: datacommons.Triple
	(*Triples)(nil),              // 1: datacommons.Triples
	(*PropertyLabels)(nil),       // 2: datacommons.PropertyLabels
	nil,                          // 3: datacommons.Triples.InNodesEntry
	nil,                          // 4: datacommons.Triples.OutNodesEntry
	(*EntityInfoCollection)(nil), // 5: datacommons.EntityInfoCollection
}
var file_node_proto_depIdxs = []int32{
	0, // 0: datacommons.Triples.triples:type_name -> datacommons.Triple
	3, // 1: datacommons.Triples.in_nodes:type_name -> datacommons.Triples.InNodesEntry
	4, // 2: datacommons.Triples.out_nodes:type_name -> datacommons.Triples.OutNodesEntry
	5, // 3: datacommons.Triples.InNodesEntry.value:type_name -> datacommons.EntityInfoCollection
	5, // 4: datacommons.Triples.OutNodesEntry.value:type_name -> datacommons.EntityInfoCollection
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	file_entity_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
