// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//  **** IMPORTANT NOTE ****
//
//  The proto of BT data has to match exactly the g3 proto, including tag
//  number.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: recon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lists of entities (with their known IDs) for a given {idProp, idVal}.
type ReconEntities struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Entities      []*ReconEntities_Entity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconEntities) Reset() {
	*x = ReconEntities{}
	mi := &file_recon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconEntities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconEntities) ProtoMessage() {}

func (x *ReconEntities) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconEntities.ProtoReflect.Descriptor instead.
func (*ReconEntities) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{0}
}

func (x *ReconEntities) GetEntities() []*ReconEntities_Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

// A list of candidate places that a coordinate might be contained in.
type CoordinateRecon struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Places        []*CoordinateRecon_Place `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinateRecon) Reset() {
	*x = CoordinateRecon{}
	mi := &file_recon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinateRecon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinateRecon) ProtoMessage() {}

func (x *CoordinateRecon) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinateRecon.ProtoReflect.Descriptor instead.
func (*CoordinateRecon) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{1}
}

func (x *CoordinateRecon) GetPlaces() []*CoordinateRecon_Place {
	if x != nil {
		return x.Places
	}
	return nil
}

type ResolveEntitiesRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Entities []*EntitySubGraph      `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	// The properties of IDs to find. If empty, all known IDs are returned.
	WantedIdProperties []string `protobuf:"bytes,2,rep,name=wanted_id_properties,json=wantedIdProperties,proto3" json:"wanted_id_properties,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResolveEntitiesRequest) Reset() {
	*x = ResolveEntitiesRequest{}
	mi := &file_recon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEntitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEntitiesRequest) ProtoMessage() {}

func (x *ResolveEntitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEntitiesRequest.ProtoReflect.Descriptor instead.
func (*ResolveEntitiesRequest) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveEntitiesRequest) GetEntities() []*EntitySubGraph {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *ResolveEntitiesRequest) GetWantedIdProperties() []string {
	if x != nil {
		return x.WantedIdProperties
	}
	return nil
}

type ResolveEntitiesResponse struct {
	state            protoimpl.MessageState                    `protogen:"open.v1"`
	ResolvedEntities []*ResolveEntitiesResponse_ResolvedEntity `protobuf:"bytes,1,rep,name=resolved_entities,json=resolvedEntities,proto3" json:"resolved_entities,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResolveEntitiesResponse) Reset() {
	*x = ResolveEntitiesResponse{}
	mi := &file_recon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEntitiesResponse) ProtoMessage() {}

func (x *ResolveEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEntitiesResponse.ProtoReflect.Descriptor instead.
func (*ResolveEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveEntitiesResponse) GetResolvedEntities() []*ResolveEntitiesResponse_ResolvedEntity {
	if x != nil {
		return x.ResolvedEntities
	}
	return nil
}

type ResolveCoordinatesRequest struct {
	state       protoimpl.MessageState                  `protogen:"open.v1"`
	Coordinates []*ResolveCoordinatesRequest_Coordinate `protobuf:"bytes,1,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	// If set only these place types are returned.
	PlaceTypes    []string `protobuf:"bytes,2,rep,name=place_types,json=placeTypes,proto3" json:"place_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveCoordinatesRequest) Reset() {
	*x = ResolveCoordinatesRequest{}
	mi := &file_recon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCoordinatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCoordinatesRequest) ProtoMessage() {}

func (x *ResolveCoordinatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCoordinatesRequest.ProtoReflect.Descriptor instead.
func (*ResolveCoordinatesRequest) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveCoordinatesRequest) GetCoordinates() []*ResolveCoordinatesRequest_Coordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *ResolveCoordinatesRequest) GetPlaceTypes() []string {
	if x != nil {
		return x.PlaceTypes
	}
	return nil
}

type ResolveCoordinatesResponse struct {
	state            protoimpl.MessageState                        `protogen:"open.v1"`
	PlaceCoordinates []*ResolveCoordinatesResponse_PlaceCoordinate `protobuf:"bytes,1,rep,name=place_coordinates,json=placeCoordinates,proto3" json:"place_coordinates,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResolveCoordinatesResponse) Reset() {
	*x = ResolveCoordinatesResponse{}
	mi := &file_recon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCoordinatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCoordinatesResponse) ProtoMessage() {}

func (x *ResolveCoordinatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCoordinatesResponse.ProtoReflect.Descriptor instead.
func (*ResolveCoordinatesResponse) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveCoordinatesResponse) GetPlaceCoordinates() []*ResolveCoordinatesResponse_PlaceCoordinate {
	if x != nil {
		return x.PlaceCoordinates
	}
	return nil
}

type ResolveIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InProp        string                 `protobuf:"bytes,1,opt,name=in_prop,json=inProp,proto3" json:"in_prop,omitempty"`
	OutProp       string                 `protobuf:"bytes,2,opt,name=out_prop,json=outProp,proto3" json:"out_prop,omitempty"`
	Ids           []string               `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveIdsRequest) Reset() {
	*x = ResolveIdsRequest{}
	mi := &file_recon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIdsRequest) ProtoMessage() {}

func (x *ResolveIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIdsRequest.ProtoReflect.Descriptor instead.
func (*ResolveIdsRequest) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveIdsRequest) GetInProp() string {
	if x != nil {
		return x.InProp
	}
	return ""
}

func (x *ResolveIdsRequest) GetOutProp() string {
	if x != nil {
		return x.OutProp
	}
	return ""
}

func (x *ResolveIdsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ResolveIdsResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Entities      []*ResolveIdsResponse_Entity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveIdsResponse) Reset() {
	*x = ResolveIdsResponse{}
	mi := &file_recon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIdsResponse) ProtoMessage() {}

func (x *ResolveIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIdsResponse.ProtoReflect.Descriptor instead.
func (*ResolveIdsResponse) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveIdsResponse) GetEntities() []*ResolveIdsResponse_Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type FindEntitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dcids         []string               `protobuf:"bytes,1,rep,name=dcids,proto3" json:"dcids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindEntitiesResponse) Reset() {
	*x = FindEntitiesResponse{}
	mi := &file_recon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindEntitiesResponse) ProtoMessage() {}

func (x *FindEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindEntitiesResponse.ProtoReflect.Descriptor instead.
func (*FindEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{8}
}

func (x *FindEntitiesResponse) GetDcids() []string {
	if x != nil {
		return x.Dcids
	}
	return nil
}

type BulkFindEntitiesRequest struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Entities      []*BulkFindEntitiesRequest_Entity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkFindEntitiesRequest) Reset() {
	*x = BulkFindEntitiesRequest{}
	mi := &file_recon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkFindEntitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkFindEntitiesRequest) ProtoMessage() {}

func (x *BulkFindEntitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkFindEntitiesRequest.ProtoReflect.Descriptor instead.
func (*BulkFindEntitiesRequest) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{9}
}

func (x *BulkFindEntitiesRequest) GetEntities() []*BulkFindEntitiesRequest_Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type BulkFindEntitiesResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Entities      []*BulkFindEntitiesResponse_Entity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkFindEntitiesResponse) Reset() {
	*x = BulkFindEntitiesResponse{}
	mi := &file_recon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkFindEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkFindEntitiesResponse) ProtoMessage() {}

func (x *BulkFindEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkFindEntitiesResponse.ProtoReflect.Descriptor instead.
func (*BulkFindEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{10}
}

func (x *BulkFindEntitiesResponse) GetEntities() []*BulkFindEntitiesResponse_Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type RecognizePlacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queries       []string               `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizePlacesRequest) Reset() {
	*x = RecognizePlacesRequest{}
	mi := &file_recon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizePlacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizePlacesRequest) ProtoMessage() {}

func (x *RecognizePlacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizePlacesRequest.ProtoReflect.Descriptor instead.
func (*RecognizePlacesRequest) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{11}
}

func (x *RecognizePlacesRequest) GetQueries() []string {
	if x != nil {
		return x.Queries
	}
	return nil
}

type RecognizePlacesResponse struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	QueryItems    map[string]*RecognizePlacesResponse_Items `protobuf:"bytes,1,rep,name=query_items,json=queryItems,proto3" json:"query_items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizePlacesResponse) Reset() {
	*x = RecognizePlacesResponse{}
	mi := &file_recon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizePlacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizePlacesResponse) ProtoMessage() {}

func (x *RecognizePlacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizePlacesResponse.ProtoReflect.Descriptor instead.
func (*RecognizePlacesResponse) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{12}
}

func (x *RecognizePlacesResponse) GetQueryItems() map[string]*RecognizePlacesResponse_Items {
	if x != nil {
		return x.QueryItems
	}
	return nil
}

// RecogPlace contains info of a place for RecognizePlaces method.
type RecogPlace struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Names            []*RecogPlace_Name     `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	Dcid             string                 `protobuf:"bytes,2,opt,name=dcid,proto3" json:"dcid,omitempty"`
	ContainingPlaces []string               `protobuf:"bytes,3,rep,name=containing_places,json=containingPlaces,proto3" json:"containing_places,omitempty"`
	Population       int64                  `protobuf:"varint,4,opt,name=population,proto3" json:"population,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecogPlace) Reset() {
	*x = RecogPlace{}
	mi := &file_recon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecogPlace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecogPlace) ProtoMessage() {}

func (x *RecogPlace) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecogPlace.ProtoReflect.Descriptor instead.
func (*RecogPlace) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{13}
}

func (x *RecogPlace) GetNames() []*RecogPlace_Name {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *RecogPlace) GetDcid() string {
	if x != nil {
		return x.Dcid
	}
	return ""
}

func (x *RecogPlace) GetContainingPlaces() []string {
	if x != nil {
		return x.ContainingPlaces
	}
	return nil
}

func (x *RecogPlace) GetPopulation() int64 {
	if x != nil {
		return x.Population
	}
	return 0
}

type RecogPlaces struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Places        []*RecogPlace          `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecogPlaces) Reset() {
	*x = RecogPlaces{}
	mi := &file_recon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecogPlaces) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecogPlaces) ProtoMessage() {}

func (x *RecogPlaces) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecogPlaces.ProtoReflect.Descriptor instead.
func (*RecogPlaces) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{14}
}

func (x *RecogPlaces) GetPlaces() []*RecogPlace {
	if x != nil {
		return x.Places
	}
	return nil
}

type TokenSpans struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spans         []*TokenSpans_Span     `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenSpans) Reset() {
	*x = TokenSpans{}
	mi := &file_recon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenSpans) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenSpans) ProtoMessage() {}

func (x *TokenSpans) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenSpans.ProtoReflect.Descriptor instead.
func (*TokenSpans) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{15}
}

func (x *TokenSpans) GetSpans() []*TokenSpans_Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

type ReconEntities_Entity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All known IDs of the entity, including the DCID, excluding the ID in the
	// recon request.
	// NOTE: A single ID prop might be repeated.
	Ids []*ReconEntities_Entity_ID `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	// All types of the entity. Ordered by dominant place type.
	Types         []string `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconEntities_Entity) Reset() {
	*x = ReconEntities_Entity{}
	mi := &file_recon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconEntities_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconEntities_Entity) ProtoMessage() {}

func (x *ReconEntities_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconEntities_Entity.ProtoReflect.Descriptor instead.
func (*ReconEntities_Entity) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ReconEntities_Entity) GetIds() []*ReconEntities_Entity_ID {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ReconEntities_Entity) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

type ReconEntities_Entity_ID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prop          string                 `protobuf:"bytes,1,opt,name=prop,proto3" json:"prop,omitempty"`
	Val           string                 `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconEntities_Entity_ID) Reset() {
	*x = ReconEntities_Entity_ID{}
	mi := &file_recon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconEntities_Entity_ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconEntities_Entity_ID) ProtoMessage() {}

func (x *ReconEntities_Entity_ID) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconEntities_Entity_ID.ProtoReflect.Descriptor instead.
func (*ReconEntities_Entity_ID) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ReconEntities_Entity_ID) GetProp() string {
	if x != nil {
		return x.Prop
	}
	return ""
}

func (x *ReconEntities_Entity_ID) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type CoordinateRecon_Place struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The DCIDs of the places.
	Dcid string `protobuf:"bytes,1,opt,name=dcid,proto3" json:"dcid,omitempty"`
	// If the rectangle is fully contained in the place.
	Full          bool   `protobuf:"varint,2,opt,name=full,proto3" json:"full,omitempty"`
	DominantType  string `protobuf:"bytes,3,opt,name=dominant_type,json=dominantType,proto3" json:"dominant_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinateRecon_Place) Reset() {
	*x = CoordinateRecon_Place{}
	mi := &file_recon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinateRecon_Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinateRecon_Place) ProtoMessage() {}

func (x *CoordinateRecon_Place) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinateRecon_Place.ProtoReflect.Descriptor instead.
func (*CoordinateRecon_Place) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CoordinateRecon_Place) GetDcid() string {
	if x != nil {
		return x.Dcid
	}
	return ""
}

func (x *CoordinateRecon_Place) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

func (x *CoordinateRecon_Place) GetDominantType() string {
	if x != nil {
		return x.DominantType
	}
	return ""
}

type ResolveEntitiesResponse_ResolvedId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []*IdWithProperty      `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Probability   float64                `protobuf:"fixed64,2,opt,name=probability,proto3" json:"probability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveEntitiesResponse_ResolvedId) Reset() {
	*x = ResolveEntitiesResponse_ResolvedId{}
	mi := &file_recon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEntitiesResponse_ResolvedId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEntitiesResponse_ResolvedId) ProtoMessage() {}

func (x *ResolveEntitiesResponse_ResolvedId) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEntitiesResponse_ResolvedId.ProtoReflect.Descriptor instead.
func (*ResolveEntitiesResponse_ResolvedId) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ResolveEntitiesResponse_ResolvedId) GetIds() []*IdWithProperty {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ResolveEntitiesResponse_ResolvedId) GetProbability() float64 {
	if x != nil {
		return x.Probability
	}
	return 0
}

type ResolveEntitiesResponse_ResolvedEntity struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	SourceId      string                                `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	ResolvedIds   []*ResolveEntitiesResponse_ResolvedId `protobuf:"bytes,2,rep,name=resolved_ids,json=resolvedIds,proto3" json:"resolved_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveEntitiesResponse_ResolvedEntity) Reset() {
	*x = ResolveEntitiesResponse_ResolvedEntity{}
	mi := &file_recon_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEntitiesResponse_ResolvedEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEntitiesResponse_ResolvedEntity) ProtoMessage() {}

func (x *ResolveEntitiesResponse_ResolvedEntity) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEntitiesResponse_ResolvedEntity.ProtoReflect.Descriptor instead.
func (*ResolveEntitiesResponse_ResolvedEntity) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ResolveEntitiesResponse_ResolvedEntity) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *ResolveEntitiesResponse_ResolvedEntity) GetResolvedIds() []*ResolveEntitiesResponse_ResolvedId {
	if x != nil {
		return x.ResolvedIds
	}
	return nil
}

type ResolveCoordinatesRequest_Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveCoordinatesRequest_Coordinate) Reset() {
	*x = ResolveCoordinatesRequest_Coordinate{}
	mi := &file_recon_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCoordinatesRequest_Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCoordinatesRequest_Coordinate) ProtoMessage() {}

func (x *ResolveCoordinatesRequest_Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCoordinatesRequest_Coordinate.ProtoReflect.Descriptor instead.
func (*ResolveCoordinatesRequest_Coordinate) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ResolveCoordinatesRequest_Coordinate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ResolveCoordinatesRequest_Coordinate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type ResolveCoordinatesResponse_Place struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dcid          string                 `protobuf:"bytes,1,opt,name=dcid,proto3" json:"dcid,omitempty"`
	DominantType  string                 `protobuf:"bytes,2,opt,name=dominant_type,json=dominantType,proto3" json:"dominant_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveCoordinatesResponse_Place) Reset() {
	*x = ResolveCoordinatesResponse_Place{}
	mi := &file_recon_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCoordinatesResponse_Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCoordinatesResponse_Place) ProtoMessage() {}

func (x *ResolveCoordinatesResponse_Place) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCoordinatesResponse_Place.ProtoReflect.Descriptor instead.
func (*ResolveCoordinatesResponse_Place) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ResolveCoordinatesResponse_Place) GetDcid() string {
	if x != nil {
		return x.Dcid
	}
	return ""
}

func (x *ResolveCoordinatesResponse_Place) GetDominantType() string {
	if x != nil {
		return x.DominantType
	}
	return ""
}

type ResolveCoordinatesResponse_PlaceCoordinate struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Latitude  float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// TODO(ws): Remove this field once confirmed no one is using it.
	// https://github.com/search?q=repo%3Adatacommonsorg%2Fdata+%2Fresolve%2Fcoordinate&type=code
	PlaceDcids    []string                            `protobuf:"bytes,3,rep,name=place_dcids,json=placeDcids,proto3" json:"place_dcids,omitempty"`
	Places        []*ResolveCoordinatesResponse_Place `protobuf:"bytes,4,rep,name=places,proto3" json:"places,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveCoordinatesResponse_PlaceCoordinate) Reset() {
	*x = ResolveCoordinatesResponse_PlaceCoordinate{}
	mi := &file_recon_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCoordinatesResponse_PlaceCoordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCoordinatesResponse_PlaceCoordinate) ProtoMessage() {}

func (x *ResolveCoordinatesResponse_PlaceCoordinate) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCoordinatesResponse_PlaceCoordinate.ProtoReflect.Descriptor instead.
func (*ResolveCoordinatesResponse_PlaceCoordinate) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{5, 1}
}

func (x *ResolveCoordinatesResponse_PlaceCoordinate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ResolveCoordinatesResponse_PlaceCoordinate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *ResolveCoordinatesResponse_PlaceCoordinate) GetPlaceDcids() []string {
	if x != nil {
		return x.PlaceDcids
	}
	return nil
}

func (x *ResolveCoordinatesResponse_PlaceCoordinate) GetPlaces() []*ResolveCoordinatesResponse_Place {
	if x != nil {
		return x.Places
	}
	return nil
}

type ResolveIdsResponse_Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InId          string                 `protobuf:"bytes,1,opt,name=in_id,json=inId,proto3" json:"in_id,omitempty"`
	OutIds        []string               `protobuf:"bytes,2,rep,name=out_ids,json=outIds,proto3" json:"out_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveIdsResponse_Entity) Reset() {
	*x = ResolveIdsResponse_Entity{}
	mi := &file_recon_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIdsResponse_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIdsResponse_Entity) ProtoMessage() {}

func (x *ResolveIdsResponse_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIdsResponse_Entity.ProtoReflect.Descriptor instead.
func (*ResolveIdsResponse_Entity) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ResolveIdsResponse_Entity) GetInId() string {
	if x != nil {
		return x.InId
	}
	return ""
}

func (x *ResolveIdsResponse_Entity) GetOutIds() []string {
	if x != nil {
		return x.OutIds
	}
	return nil
}

type BulkFindEntitiesRequest_Entity struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Description string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Optional.
	Type          string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkFindEntitiesRequest_Entity) Reset() {
	*x = BulkFindEntitiesRequest_Entity{}
	mi := &file_recon_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkFindEntitiesRequest_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkFindEntitiesRequest_Entity) ProtoMessage() {}

func (x *BulkFindEntitiesRequest_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkFindEntitiesRequest_Entity.ProtoReflect.Descriptor instead.
func (*BulkFindEntitiesRequest_Entity) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{9, 0}
}

func (x *BulkFindEntitiesRequest_Entity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BulkFindEntitiesRequest_Entity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type BulkFindEntitiesResponse_Entity struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Description string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Optional.
	Type          string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Dcids         []string `protobuf:"bytes,3,rep,name=dcids,proto3" json:"dcids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkFindEntitiesResponse_Entity) Reset() {
	*x = BulkFindEntitiesResponse_Entity{}
	mi := &file_recon_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkFindEntitiesResponse_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkFindEntitiesResponse_Entity) ProtoMessage() {}

func (x *BulkFindEntitiesResponse_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkFindEntitiesResponse_Entity.ProtoReflect.Descriptor instead.
func (*BulkFindEntitiesResponse_Entity) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{10, 0}
}

func (x *BulkFindEntitiesResponse_Entity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BulkFindEntitiesResponse_Entity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BulkFindEntitiesResponse_Entity) GetDcids() []string {
	if x != nil {
		return x.Dcids
	}
	return nil
}

type RecognizePlacesResponse_Place struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dcid          string                 `protobuf:"bytes,1,opt,name=dcid,proto3" json:"dcid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizePlacesResponse_Place) Reset() {
	*x = RecognizePlacesResponse_Place{}
	mi := &file_recon_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizePlacesResponse_Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizePlacesResponse_Place) ProtoMessage() {}

func (x *RecognizePlacesResponse_Place) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizePlacesResponse_Place.ProtoReflect.Descriptor instead.
func (*RecognizePlacesResponse_Place) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{12, 0}
}

func (x *RecognizePlacesResponse_Place) GetDcid() string {
	if x != nil {
		return x.Dcid
	}
	return ""
}

type RecognizePlacesResponse_Item struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Substring of input query.
	Span string `protobuf:"bytes,1,opt,name=span,proto3" json:"span,omitempty"`
	// Optional. Recognized places.
	Places        []*RecognizePlacesResponse_Place `protobuf:"bytes,2,rep,name=places,proto3" json:"places,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizePlacesResponse_Item) Reset() {
	*x = RecognizePlacesResponse_Item{}
	mi := &file_recon_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizePlacesResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizePlacesResponse_Item) ProtoMessage() {}

func (x *RecognizePlacesResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizePlacesResponse_Item.ProtoReflect.Descriptor instead.
func (*RecognizePlacesResponse_Item) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{12, 1}
}

func (x *RecognizePlacesResponse_Item) GetSpan() string {
	if x != nil {
		return x.Span
	}
	return ""
}

func (x *RecognizePlacesResponse_Item) GetPlaces() []*RecognizePlacesResponse_Place {
	if x != nil {
		return x.Places
	}
	return nil
}

type RecognizePlacesResponse_Items struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Items         []*RecognizePlacesResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizePlacesResponse_Items) Reset() {
	*x = RecognizePlacesResponse_Items{}
	mi := &file_recon_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizePlacesResponse_Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizePlacesResponse_Items) ProtoMessage() {}

func (x *RecognizePlacesResponse_Items) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizePlacesResponse_Items.ProtoReflect.Descriptor instead.
func (*RecognizePlacesResponse_Items) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{12, 2}
}

func (x *RecognizePlacesResponse_Items) GetItems() []*RecognizePlacesResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type RecogPlace_Name struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parts         []string               `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecogPlace_Name) Reset() {
	*x = RecogPlace_Name{}
	mi := &file_recon_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecogPlace_Name) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecogPlace_Name) ProtoMessage() {}

func (x *RecogPlace_Name) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecogPlace_Name.ProtoReflect.Descriptor instead.
func (*RecogPlace_Name) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{13, 0}
}

func (x *RecogPlace_Name) GetParts() []string {
	if x != nil {
		return x.Parts
	}
	return nil
}

type TokenSpans_Span struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Tokens []string `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	// Optional, only used when the token span contains place candidates.
	Places        []*RecogPlace `protobuf:"bytes,2,rep,name=places,proto3" json:"places,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenSpans_Span) Reset() {
	*x = TokenSpans_Span{}
	mi := &file_recon_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenSpans_Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenSpans_Span) ProtoMessage() {}

func (x *TokenSpans_Span) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenSpans_Span.ProtoReflect.Descriptor instead.
func (*TokenSpans_Span) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{15, 0}
}

func (x *TokenSpans_Span) GetTokens() []string {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *TokenSpans_Span) GetPlaces() []*RecogPlace {
	if x != nil {
		return x.Places
	}
	return nil
}

var File_recon_proto protoreflect.FileDescriptor

const file_recon_proto_rawDesc = "" +
	"\n" +
	"\vrecon.proto\x12\vdatacommons\x1a\fentity.proto\"\xd3\x01\n" +
	"\rReconEntities\x12=\n" +
	"\bentities\x18\x01 \x03(\v2!.datacommons.ReconEntities.EntityR\bentities\x1a\x82\x01\n" +
	"\x06Entity\x126\n" +
	"\x03ids\x18\x01 \x03(\v2$.datacommons.ReconEntities.Entity.IDR\x03ids\x12\x14\n" +
	"\x05types\x18\x02 \x03(\tR\x05types\x1a*\n" +
	"\x02ID\x12\x12\n" +
	"\x04prop\x18\x01 \x01(\tR\x04prop\x12\x10\n" +
	"\x03val\x18\x02 \x01(\tR\x03val\"\xa3\x01\n" +
	"\x0fCoordinateRecon\x12:\n" +
	"\x06places\x18\x01 \x03(\v2\".datacommons.CoordinateRecon.PlaceR\x06places\x1aT\n" +
	"\x05Place\x12\x12\n" +
	"\x04dcid\x18\x01 \x01(\tR\x04dcid\x12\x12\n" +
	"\x04full\x18\x02 \x01(\bR\x04full\x12#\n" +
	"\rdominant_type\x18\x03 \x01(\tR\fdominantType\"\x83\x01\n" +
	"\x16ResolveEntitiesRequest\x127\n" +
	"\bentities\x18\x01 \x03(\v2\x1b.datacommons.EntitySubGraphR\bentities\x120\n" +
	"\x14wanted_id_properties\x18\x02 \x03(\tR\x12wantedIdProperties\"\xde\x02\n" +
	"\x17ResolveEntitiesResponse\x12`\n" +
	"\x11resolved_entities\x18\x01 \x03(\v23.datacommons.ResolveEntitiesResponse.ResolvedEntityR\x10resolvedEntities\x1a]\n" +
	"\n" +
	"ResolvedId\x12-\n" +
	"\x03ids\x18\x01 \x03(\v2\x1b.datacommons.IdWithPropertyR\x03ids\x12 \n" +
	"\vprobability\x18\x02 \x01(\x01R\vprobability\x1a\x81\x01\n" +
	"\x0eResolvedEntity\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12R\n" +
	"\fresolved_ids\x18\x02 \x03(\v2/.datacommons.ResolveEntitiesResponse.ResolvedIdR\vresolvedIds\"\xd9\x01\n" +
	"\x19ResolveCoordinatesRequest\x12S\n" +
	"\vcoordinates\x18\x01 \x03(\v21.datacommons.ResolveCoordinatesRequest.CoordinateR\vcoordinates\x12\x1f\n" +
	"\vplace_types\x18\x02 \x03(\tR\n" +
	"placeTypes\x1aF\n" +
	"\n" +
	"Coordinate\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"\xfa\x02\n" +
	"\x1aResolveCoordinatesResponse\x12d\n" +
	"\x11place_coordinates\x18\x01 \x03(\v27.datacommons.ResolveCoordinatesResponse.PlaceCoordinateR\x10placeCoordinates\x1a@\n" +
	"\x05Place\x12\x12\n" +
	"\x04dcid\x18\x01 \x01(\tR\x04dcid\x12#\n" +
	"\rdominant_type\x18\x02 \x01(\tR\fdominantType\x1a\xb3\x01\n" +
	"\x0fPlaceCoordinate\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1f\n" +
	"\vplace_dcids\x18\x03 \x03(\tR\n" +
	"placeDcids\x12E\n" +
	"\x06places\x18\x04 \x03(\v2-.datacommons.ResolveCoordinatesResponse.PlaceR\x06places\"Y\n" +
	"\x11ResolveIdsRequest\x12\x17\n" +
	"\ain_prop\x18\x01 \x01(\tR\x06inProp\x12\x19\n" +
	"\bout_prop\x18\x02 \x01(\tR\aoutProp\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\tR\x03ids\"\x90\x01\n" +
	"\x12ResolveIdsResponse\x12B\n" +
	"\bentities\x18\x01 \x03(\v2&.datacommons.ResolveIdsResponse.EntityR\bentities\x1a6\n" +
	"\x06Entity\x12\x13\n" +
	"\x05in_id\x18\x01 \x01(\tR\x04inId\x12\x17\n" +
	"\aout_ids\x18\x02 \x03(\tR\x06outIds\",\n" +
	"\x14FindEntitiesResponse\x12\x14\n" +
	"\x05dcids\x18\x01 \x03(\tR\x05dcids\"\xa2\x01\n" +
	"\x17BulkFindEntitiesRequest\x12G\n" +
	"\bentities\x18\x01 \x03(\v2+.datacommons.BulkFindEntitiesRequest.EntityR\bentities\x1a>\n" +
	"\x06Entity\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\xba\x01\n" +
	"\x18BulkFindEntitiesResponse\x12H\n" +
	"\bentities\x18\x01 \x03(\v2,.datacommons.BulkFindEntitiesResponse.EntityR\bentities\x1aT\n" +
	"\x06Entity\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05dcids\x18\x03 \x03(\tR\x05dcids\"2\n" +
	"\x16RecognizePlacesRequest\x12\x18\n" +
	"\aqueries\x18\x01 \x03(\tR\aqueries\"\xa2\x03\n" +
	"\x17RecognizePlacesResponse\x12U\n" +
	"\vquery_items\x18\x01 \x03(\v24.datacommons.RecognizePlacesResponse.QueryItemsEntryR\n" +
	"queryItems\x1a\x1b\n" +
	"\x05Place\x12\x12\n" +
	"\x04dcid\x18\x01 \x01(\tR\x04dcid\x1a^\n" +
	"\x04Item\x12\x12\n" +
	"\x04span\x18\x01 \x01(\tR\x04span\x12B\n" +
	"\x06places\x18\x02 \x03(\v2*.datacommons.RecognizePlacesResponse.PlaceR\x06places\x1aH\n" +
	"\x05Items\x12?\n" +
	"\x05items\x18\x01 \x03(\v2).datacommons.RecognizePlacesResponse.ItemR\x05items\x1ai\n" +
	"\x0fQueryItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12@\n" +
	"\x05value\x18\x02 \x01(\v2*.datacommons.RecognizePlacesResponse.ItemsR\x05value:\x028\x01\"\xbf\x01\n" +
	"\n" +
	"RecogPlace\x122\n" +
	"\x05names\x18\x01 \x03(\v2\x1c.datacommons.RecogPlace.NameR\x05names\x12\x12\n" +
	"\x04dcid\x18\x02 \x01(\tR\x04dcid\x12+\n" +
	"\x11containing_places\x18\x03 \x03(\tR\x10containingPlaces\x12\x1e\n" +
	"\n" +
	"population\x18\x04 \x01(\x03R\n" +
	"population\x1a\x1c\n" +
	"\x04Name\x12\x14\n" +
	"\x05parts\x18\x01 \x03(\tR\x05parts\">\n" +
	"\vRecogPlaces\x12/\n" +
	"\x06places\x18\x01 \x03(\v2\x17.datacommons.RecogPlaceR\x06places\"\x91\x01\n" +
	"\n" +
	"TokenSpans\x122\n" +
	"\x05spans\x18\x01 \x03(\v2\x1c.datacommons.TokenSpans.SpanR\x05spans\x1aO\n" +
	"\x04Span\x12\x16\n" +
	"\x06tokens\x18\x01 \x03(\tR\x06tokens\x12/\n" +
	"\x06places\x18\x02 \x03(\v2\x17.datacommons.RecogPlaceR\x06placesB0Z.github.com/datacommonsorg/mixer/internal/protob\x06proto3"

var (
	file_recon_proto_rawDescOnce sync.Once
	file_recon_proto_rawDescData []byte
)

func file_recon_proto_rawDescGZIP() []byte {
	file_recon_proto_rawDescOnce.Do(func() {
		file_recon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recon_proto_rawDesc), len(file_recon_proto_rawDesc)))
	})
	return file_recon_proto_rawDescData
}

var file_recon_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_recon_proto_goTypes = []any{
	(*ReconEntities)(nil),                              // 0: datacommons.ReconEntities
	(*CoordinateRecon)(nil),                            // 1: datacommons.CoordinateRecon
	(*ResolveEntitiesRequest)(nil),                     // 2: datacommons.ResolveEntitiesRequest
	(*ResolveEntitiesResponse)(nil),                    // 3: datacommons.ResolveEntitiesResponse
	(*ResolveCoordinatesRequest)(nil),                  // 4: datacommons.ResolveCoordinatesRequest
	(*ResolveCoordinatesResponse)(nil),                 // 5: datacommons.ResolveCoordinatesResponse
	(*ResolveIdsRequest)(nil),                          // 6: datacommons.ResolveIdsRequest
	(*ResolveIdsResponse)(nil),                         // 7: datacommons.ResolveIdsResponse
	(*FindEntitiesResponse)(nil),                       // 8: datacommons.FindEntitiesResponse
	(*BulkFindEntitiesRequest)(nil),                    // 9: datacommons.BulkFindEntitiesRequest
	(*BulkFindEntitiesResponse)(nil),                   // 10: datacommons.BulkFindEntitiesResponse
	(*RecognizePlacesRequest)(nil),                     // 11: datacommons.RecognizePlacesRequest
	(*RecognizePlacesResponse)(nil),                    // 12: datacommons.RecognizePlacesResponse
	(*RecogPlace)(nil),                                 // 13: datacommons.RecogPlace
	(*RecogPlaces)(nil),                                // 14: datacommons.RecogPlaces
	(*TokenSpans)(nil),                                 // 15: datacommons.TokenSpans
	(*ReconEntities_Entity)(nil),                       // 16: datacommons.ReconEntities.Entity
	(*ReconEntities_Entity_ID)(nil),                    // 17: datacommons.ReconEntities.Entity.ID
	(*CoordinateRecon_Place)(nil),                      // 18: datacommons.CoordinateRecon.Place
	(*ResolveEntitiesResponse_ResolvedId)(nil),         // 19: datacommons.ResolveEntitiesResponse.ResolvedId
	(*ResolveEntitiesResponse_ResolvedEntity)(nil),     // 20: datacommons.ResolveEntitiesResponse.ResolvedEntity
	(*ResolveCoordinatesRequest_Coordinate)(nil),       // 21: datacommons.ResolveCoordinatesRequest.Coordinate
	(*ResolveCoordinatesResponse_Place)(nil),           // 22: datacommons.ResolveCoordinatesResponse.Place
	(*ResolveCoordinatesResponse_PlaceCoordinate)(nil), // 23: datacommons.ResolveCoordinatesResponse.PlaceCoordinate
	(*ResolveIdsResponse_Entity)(nil),                  // 24: datacommons.ResolveIdsResponse.Entity
	(*BulkFindEntitiesRequest_Entity)(nil),             // 25: datacommons.BulkFindEntitiesRequest.Entity
	(*BulkFindEntitiesResponse_Entity)(nil),            // 26: datacommons.BulkFindEntitiesResponse.Entity
	(*RecognizePlacesResponse_Place)(nil),              // 27: datacommons.RecognizePlacesResponse.Place
	(*RecognizePlacesResponse_Item)(nil),               // 28: datacommons.RecognizePlacesResponse.Item
	(*RecognizePlacesResponse_Items)(nil),              // 29: datacommons.RecognizePlacesResponse.Items
	nil,                                                // 30: datacommons.RecognizePlacesResponse.QueryItemsEntry
	(*RecogPlace_Name)(nil),                            // 31: datacommons.RecogPlace.Name
	(*TokenSpans_Span)(nil),                            // 32: datacommons.TokenSpans.Span
	(*EntitySubGraph)(nil),                             // 33: datacommons.EntitySubGraph
	(*IdWithProperty)(nil),                             // 34: datacommons.IdWithProperty
}
var file_recon_proto_depIdxs = []int32{
	16, // 0: datacommons.ReconEntities.entities:type_name -> datacommons.ReconEntities.Entity
	18, // 1: datacommons.CoordinateRecon.places:type_name -> datacommons.CoordinateRecon.Place
	33, // 2: datacommons.ResolveEntitiesRequest.entities:type_name -> datacommons.EntitySubGraph
	20, // 3: datacommons.ResolveEntitiesResponse.resolved_entities:type_name -> datacommons.ResolveEntitiesResponse.ResolvedEntity
	21, // 4: datacommons.ResolveCoordinatesRequest.coordinates:type_name -> datacommons.ResolveCoordinatesRequest.Coordinate
	23, // 5: datacommons.ResolveCoordinatesResponse.place_coordinates:type_name -> datacommons.ResolveCoordinatesResponse.PlaceCoordinate
	24, // 6: datacommons.ResolveIdsResponse.entities:type_name -> datacommons.ResolveIdsResponse.Entity
	25, // 7: datacommons.BulkFindEntitiesRequest.entities:type_name -> datacommons.BulkFindEntitiesRequest.Entity
	26, // 8: datacommons.BulkFindEntitiesResponse.entities:type_name -> datacommons.BulkFindEntitiesResponse.Entity
	30, // 9: datacommons.RecognizePlacesResponse.query_items:type_name -> datacommons.RecognizePlacesResponse.QueryItemsEntry
	31, // 10: datacommons.RecogPlace.names:type_name -> datacommons.RecogPlace.Name
	13, // 11: datacommons.RecogPlaces.places:type_name -> datacommons.RecogPlace
	32, // 12: datacommons.TokenSpans.spans:type_name -> datacommons.TokenSpans.Span
	17, // 13: datacommons.ReconEntities.Entity.ids:type_name -> datacommons.ReconEntities.Entity.ID
	34, // 14: datacommons.ResolveEntitiesResponse.ResolvedId.ids:type_name -> datacommons.IdWithProperty
	19, // 15: datacommons.ResolveEntitiesResponse.ResolvedEntity.resolved_ids:type_name -> datacommons.ResolveEntitiesResponse.ResolvedId
	22, // 16: datacommons.ResolveCoordinatesResponse.PlaceCoordinate.places:type_name -> datacommons.ResolveCoordinatesResponse.Place
	27, // 17: datacommons.RecognizePlacesResponse.Item.places:type_name -> datacommons.RecognizePlacesResponse.Place
	28, // 18: datacommons.RecognizePlacesResponse.Items.items:type_name -> datacommons.RecognizePlacesResponse.Item
	29, // 19: datacommons.RecognizePlacesResponse.QueryItemsEntry.value:type_name -> datacommons.RecognizePlacesResponse.Items
	13, // 20: datacommons.TokenSpans.Span.places:type_name -> datacommons.RecogPlace
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_recon_proto_init() }
func file_recon_proto_init() {
	if File_recon_proto != nil {
		return
	}
	file_entity_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recon_proto_rawDesc), len(file_recon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_recon_proto_goTypes,
		DependencyIndexes: file_recon_proto_depIdxs,
		MessageInfos:      file_recon_proto_msgTypes,
	}.Build()
	File_recon_proto = out.File
	file_recon_proto_goTypes = nil
	file_recon_proto_depIdxs = nil
}
