// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: v2/agent.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request payload for the resolve_places tool endpoint.
type ResolvePlacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Places        []string               `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
	Target        *string                `protobuf:"bytes,2,opt,name=target,proto3,oneof" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvePlacesRequest) Reset() {
	*x = ResolvePlacesRequest{}
	mi := &file_v2_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePlacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePlacesRequest) ProtoMessage() {}

func (x *ResolvePlacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePlacesRequest.ProtoReflect.Descriptor instead.
func (*ResolvePlacesRequest) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ResolvePlacesRequest) GetPlaces() []string {
	if x != nil {
		return x.Places
	}
	return nil
}

func (x *ResolvePlacesRequest) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

// Response payload for the resolve_places tool endpoint.
type ResolvePlacesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ResolvedPlaces *Table                 `protobuf:"bytes,2,opt,name=resolved_places,json=resolvedPlaces,proto3" json:"resolved_places,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolvePlacesResponse) Reset() {
	*x = ResolvePlacesResponse{}
	mi := &file_v2_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePlacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePlacesResponse) ProtoMessage() {}

func (x *ResolvePlacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePlacesResponse.ProtoReflect.Descriptor instead.
func (*ResolvePlacesResponse) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ResolvePlacesResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResolvePlacesResponse) GetResolvedPlaces() *Table {
	if x != nil {
		return x.ResolvedPlaces
	}
	return nil
}

// Request payload for the search_indicators tool endpoint.
type SearchIndicatorsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Query string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Deprecated: Marked as deprecated in v2/agent.proto.
	Places []string `protobuf:"bytes,2,rep,name=places,proto3" json:"places,omitempty"`
	// Deprecated: Marked as deprecated in v2/agent.proto.
	ParentPlace    string `protobuf:"bytes,3,opt,name=parent_place,json=parentPlace,proto3" json:"parent_place,omitempty"`
	PerSearchLimit int32  `protobuf:"varint,4,opt,name=per_search_limit,json=perSearchLimit,proto3" json:"per_search_limit,omitempty"`
	IncludeTopics  *bool  `protobuf:"varint,5,opt,name=include_topics,json=includeTopics,proto3,oneof" json:"include_topics,omitempty"`
	ExpandTopics   *bool  `protobuf:"varint,6,opt,name=expand_topics,json=expandTopics,proto3,oneof" json:"expand_topics,omitempty"`
	// Optional target for indicator resolution ("custom_only", "base_only", "base_and_custom").
	Target *string `protobuf:"bytes,7,opt,name=target,proto3,oneof" json:"target,omitempty"`
	// Resolved place DCIDs for indicator data availability filtering.
	PlaceDcids    []string `protobuf:"bytes,8,rep,name=place_dcids,json=placeDcids,proto3" json:"place_dcids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchIndicatorsRequest) Reset() {
	*x = SearchIndicatorsRequest{}
	mi := &file_v2_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchIndicatorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchIndicatorsRequest) ProtoMessage() {}

func (x *SearchIndicatorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchIndicatorsRequest.ProtoReflect.Descriptor instead.
func (*SearchIndicatorsRequest) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{2}
}

func (x *SearchIndicatorsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// Deprecated: Marked as deprecated in v2/agent.proto.
func (x *SearchIndicatorsRequest) GetPlaces() []string {
	if x != nil {
		return x.Places
	}
	return nil
}

// Deprecated: Marked as deprecated in v2/agent.proto.
func (x *SearchIndicatorsRequest) GetParentPlace() string {
	if x != nil {
		return x.ParentPlace
	}
	return ""
}

func (x *SearchIndicatorsRequest) GetPerSearchLimit() int32 {
	if x != nil {
		return x.PerSearchLimit
	}
	return 0
}

func (x *SearchIndicatorsRequest) GetIncludeTopics() bool {
	if x != nil && x.IncludeTopics != nil {
		return *x.IncludeTopics
	}
	return false
}

func (x *SearchIndicatorsRequest) GetExpandTopics() bool {
	if x != nil && x.ExpandTopics != nil {
		return *x.ExpandTopics
	}
	return false
}

func (x *SearchIndicatorsRequest) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

func (x *SearchIndicatorsRequest) GetPlaceDcids() []string {
	if x != nil {
		return x.PlaceDcids
	}
	return nil
}

// Response payload for the search_indicators tool endpoint.
type SearchIndicatorsResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Deprecated: Marked as deprecated in v2/agent.proto.
	DcidNameMappings map[string]string `protobuf:"bytes,2,rep,name=dcid_name_mappings,json=dcidNameMappings,proto3" json:"dcid_name_mappings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Deprecated: Marked as deprecated in v2/agent.proto.
	DcidPlaceTypeMappings map[string]*structpb.ListValue `protobuf:"bytes,3,rep,name=dcid_place_type_mappings,json=dcidPlaceTypeMappings,proto3" json:"dcid_place_type_mappings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Deprecated: Marked as deprecated in v2/agent.proto.
	Topics []*SearchIndicatorsResponse_Topic `protobuf:"bytes,4,rep,name=topics,proto3" json:"topics,omitempty"`
	// Deprecated: Marked as deprecated in v2/agent.proto.
	Variables []*SearchIndicatorsResponse_Variable `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty"`
	// Deprecated: Marked as deprecated in v2/agent.proto.
	ResolvedParentPlace *SearchIndicatorsResponse_ResolvedPlace `protobuf:"bytes,6,opt,name=resolved_parent_place,json=resolvedParentPlace,proto3" json:"resolved_parent_place,omitempty"`
	// Topics Table (columns: ["dcid", "name", "placesWithData", "memberTopics", "memberVariables"])
	TopicCandidates *Table `protobuf:"bytes,7,opt,name=topic_candidates,json=topicCandidates,proto3" json:"topic_candidates,omitempty"`
	// Variables Table (columns: ["dcid", "name", "placesWithData", "observationProperties"])
	VariableCandidates *Table `protobuf:"bytes,8,opt,name=variable_candidates,json=variableCandidates,proto3" json:"variable_candidates,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SearchIndicatorsResponse) Reset() {
	*x = SearchIndicatorsResponse{}
	mi := &file_v2_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchIndicatorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchIndicatorsResponse) ProtoMessage() {}

func (x *SearchIndicatorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchIndicatorsResponse.ProtoReflect.Descriptor instead.
func (*SearchIndicatorsResponse) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{3}
}

func (x *SearchIndicatorsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Deprecated: Marked as deprecated in v2/agent.proto.
func (x *SearchIndicatorsResponse) GetDcidNameMappings() map[string]string {
	if x != nil {
		return x.DcidNameMappings
	}
	return nil
}

// Deprecated: Marked as deprecated in v2/agent.proto.
func (x *SearchIndicatorsResponse) GetDcidPlaceTypeMappings() map[string]*structpb.ListValue {
	if x != nil {
		return x.DcidPlaceTypeMappings
	}
	return nil
}

// Deprecated: Marked as deprecated in v2/agent.proto.
func (x *SearchIndicatorsResponse) GetTopics() []*SearchIndicatorsResponse_Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

// Deprecated: Marked as deprecated in v2/agent.proto.
func (x *SearchIndicatorsResponse) GetVariables() []*SearchIndicatorsResponse_Variable {
	if x != nil {
		return x.Variables
	}
	return nil
}

// Deprecated: Marked as deprecated in v2/agent.proto.
func (x *SearchIndicatorsResponse) GetResolvedParentPlace() *SearchIndicatorsResponse_ResolvedPlace {
	if x != nil {
		return x.ResolvedParentPlace
	}
	return nil
}

func (x *SearchIndicatorsResponse) GetTopicCandidates() *Table {
	if x != nil {
		return x.TopicCandidates
	}
	return nil
}

func (x *SearchIndicatorsResponse) GetVariableCandidates() *Table {
	if x != nil {
		return x.VariableCandidates
	}
	return nil
}

type EntityList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dcids         []string               `protobuf:"bytes,1,rep,name=dcids,proto3" json:"dcids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityList) Reset() {
	*x = EntityList{}
	mi := &file_v2_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityList) ProtoMessage() {}

func (x *EntityList) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityList.ProtoReflect.Descriptor instead.
func (*EntityList) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{4}
}

func (x *EntityList) GetDcids() []string {
	if x != nil {
		return x.Dcids
	}
	return nil
}

// Generic tabular structure for token-efficient data delivery.
type Table struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*structpb.ListValue  `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_v2_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Table) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Table) GetRows() []*structpb.ListValue {
	if x != nil {
		return x.Rows
	}
	return nil
}

// Request payload for the get_observations tool endpoint.
type GetObservationsRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	VariableDcid string                 `protobuf:"bytes,1,opt,name=variable_dcid,json=variableDcid,proto3" json:"variable_dcid,omitempty"`
	// Deprecated: Use 'entities' map for specifying target places or multi-entity slots.
	//
	// Deprecated: Marked as deprecated in v2/agent.proto.
	PlaceDcid string `protobuf:"bytes,2,opt,name=place_dcid,json=placeDcid,proto3" json:"place_dcid,omitempty"`
	// Deprecated: Legacy single-place expansion. Multi-slot child expansion will specify target slots once native SDMX hierarchy resolution is implemented.
	//
	// Deprecated: Marked as deprecated in v2/agent.proto.
	ChildPlaceType *string `protobuf:"bytes,3,opt,name=child_place_type,json=childPlaceType,proto3,oneof" json:"child_place_type,omitempty"`
	SourceOverride *string `protobuf:"bytes,4,opt,name=source_override,json=sourceOverride,proto3,oneof" json:"source_override,omitempty"`
	Date           *string `protobuf:"bytes,5,opt,name=date,proto3,oneof" json:"date,omitempty"` // accepts "latest", "all", "range", or specific date string.
	DateRangeStart *string `protobuf:"bytes,6,opt,name=date_range_start,json=dateRangeStart,proto3,oneof" json:"date_range_start,omitempty"`
	DateRangeEnd   *string `protobuf:"bytes,7,opt,name=date_range_end,json=dateRangeEnd,proto3,oneof" json:"date_range_end,omitempty"`
	// Map of entity dimension keys (e.g. "observationAbout", "sourceCountry") to entity specifications.
	// The value is a google.protobuf.Value representing either:
	//   - Direct DCIDs list: a JSON array of strings.
	//     Example: "observationAbout": ["geoId/06", "geoId/48"]
	//   - Parent place constraint: a JSON object containing "parent_dcid" and "child_type" keys.
	//     Example: "observationAbout": {"parent_dcid": "geoId/06", "child_type": "County"}
	Entities      map[string]*structpb.Value `protobuf:"bytes,8,rep,name=entities,proto3" json:"entities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObservationsRequest) Reset() {
	*x = GetObservationsRequest{}
	mi := &file_v2_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObservationsRequest) ProtoMessage() {}

func (x *GetObservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObservationsRequest.ProtoReflect.Descriptor instead.
func (*GetObservationsRequest) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{6}
}

func (x *GetObservationsRequest) GetVariableDcid() string {
	if x != nil {
		return x.VariableDcid
	}
	return ""
}

// Deprecated: Marked as deprecated in v2/agent.proto.
func (x *GetObservationsRequest) GetPlaceDcid() string {
	if x != nil {
		return x.PlaceDcid
	}
	return ""
}

// Deprecated: Marked as deprecated in v2/agent.proto.
func (x *GetObservationsRequest) GetChildPlaceType() string {
	if x != nil && x.ChildPlaceType != nil {
		return *x.ChildPlaceType
	}
	return ""
}

func (x *GetObservationsRequest) GetSourceOverride() string {
	if x != nil && x.SourceOverride != nil {
		return *x.SourceOverride
	}
	return ""
}

func (x *GetObservationsRequest) GetDate() string {
	if x != nil && x.Date != nil {
		return *x.Date
	}
	return ""
}

func (x *GetObservationsRequest) GetDateRangeStart() string {
	if x != nil && x.DateRangeStart != nil {
		return *x.DateRangeStart
	}
	return ""
}

func (x *GetObservationsRequest) GetDateRangeEnd() string {
	if x != nil && x.DateRangeEnd != nil {
		return *x.DateRangeEnd
	}
	return ""
}

func (x *GetObservationsRequest) GetEntities() map[string]*structpb.Value {
	if x != nil {
		return x.Entities
	}
	return nil
}

// Response payload for the get_observations tool endpoint.
type GetObservationsResponse struct {
	state    protoimpl.MessageState        `protogen:"open.v1"`
	Variable *GetObservationsResponse_Node `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	// Deprecated: Parent place info will be represented as standard entity DCIDs in entity_metadata once child place resolution in SDMX is available.
	//
	// Deprecated: Marked as deprecated in v2/agent.proto.
	ResolvedParentPlace *GetObservationsResponse_Node `protobuf:"bytes,2,opt,name=resolved_parent_place,json=resolvedParentPlace,proto3" json:"resolved_parent_place,omitempty"`
	// Deprecated: Child place resolution will be handled natively in SDMX once available; use explicit entity DCIDs in 'entities' for now.
	//
	// Deprecated: Marked as deprecated in v2/agent.proto.
	ChildPlaceType string `protobuf:"bytes,3,opt,name=child_place_type,json=childPlaceType,proto3" json:"child_place_type,omitempty"`
	// Shared flat entity metadata table across all entities (columns: ["dcid", "name", "typeOf"]).
	// Encodes name and typeOf for all returned places and entities uniformly.
	EntityMetadata *Table `protobuf:"bytes,7,opt,name=entity_metadata,json=entityMetadata,proto3" json:"entity_metadata,omitempty"`
	// Observation time-series Table (columns: ["observationAbout", "date", "value"] or multi-slot names)
	Data *Table `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	// Deprecated: Use 'data' Table and 'entity_metadata' Table instead.
	//
	// Deprecated: Marked as deprecated in v2/agent.proto.
	PlaceObservations  []*GetObservationsResponse_PlaceObservation  `protobuf:"bytes,4,rep,name=place_observations,json=placeObservations,proto3" json:"place_observations,omitempty"`
	SourceMetadata     *GetObservationsResponse_FacetMetadata       `protobuf:"bytes,5,opt,name=source_metadata,json=sourceMetadata,proto3" json:"source_metadata,omitempty"`
	AlternativeSources []*GetObservationsResponse_AlternativeSource `protobuf:"bytes,6,rep,name=alternative_sources,json=alternativeSources,proto3" json:"alternative_sources,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetObservationsResponse) Reset() {
	*x = GetObservationsResponse{}
	mi := &file_v2_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObservationsResponse) ProtoMessage() {}

func (x *GetObservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObservationsResponse.ProtoReflect.Descriptor instead.
func (*GetObservationsResponse) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{7}
}

func (x *GetObservationsResponse) GetVariable() *GetObservationsResponse_Node {
	if x != nil {
		return x.Variable
	}
	return nil
}

// Deprecated: Marked as deprecated in v2/agent.proto.
func (x *GetObservationsResponse) GetResolvedParentPlace() *GetObservationsResponse_Node {
	if x != nil {
		return x.ResolvedParentPlace
	}
	return nil
}

// Deprecated: Marked as deprecated in v2/agent.proto.
func (x *GetObservationsResponse) GetChildPlaceType() string {
	if x != nil {
		return x.ChildPlaceType
	}
	return ""
}

func (x *GetObservationsResponse) GetEntityMetadata() *Table {
	if x != nil {
		return x.EntityMetadata
	}
	return nil
}

func (x *GetObservationsResponse) GetData() *Table {
	if x != nil {
		return x.Data
	}
	return nil
}

// Deprecated: Marked as deprecated in v2/agent.proto.
func (x *GetObservationsResponse) GetPlaceObservations() []*GetObservationsResponse_PlaceObservation {
	if x != nil {
		return x.PlaceObservations
	}
	return nil
}

func (x *GetObservationsResponse) GetSourceMetadata() *GetObservationsResponse_FacetMetadata {
	if x != nil {
		return x.SourceMetadata
	}
	return nil
}

func (x *GetObservationsResponse) GetAlternativeSources() []*GetObservationsResponse_AlternativeSource {
	if x != nil {
		return x.AlternativeSources
	}
	return nil
}

// Request payload for the get_variable_metadata tool endpoint.
// Both variable_dcids and entity_dcids are strictly required.
type GetVariableMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VariableDcids []string               `protobuf:"bytes,1,rep,name=variable_dcids,json=variableDcids,proto3" json:"variable_dcids,omitempty"`
	EntityDcids   []string               `protobuf:"bytes,2,rep,name=entity_dcids,json=entityDcids,proto3" json:"entity_dcids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVariableMetadataRequest) Reset() {
	*x = GetVariableMetadataRequest{}
	mi := &file_v2_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariableMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableMetadataRequest) ProtoMessage() {}

func (x *GetVariableMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetVariableMetadataRequest) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{8}
}

func (x *GetVariableMetadataRequest) GetVariableDcids() []string {
	if x != nil {
		return x.VariableDcids
	}
	return nil
}

func (x *GetVariableMetadataRequest) GetEntityDcids() []string {
	if x != nil {
		return x.EntityDcids
	}
	return nil
}

// Response payload for the get_variable_metadata tool endpoint.
type GetVariableMetadataResponse struct {
	state         protoimpl.MessageState                                     `protogen:"open.v1"`
	Status        string                                                     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Variables     map[string]*GetVariableMetadataResponse_VariableMetadata   `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Provenances   map[string]*GetVariableMetadataResponse_ProvenanceMetadata `protobuf:"bytes,3,rep,name=provenances,proto3" json:"provenances,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVariableMetadataResponse) Reset() {
	*x = GetVariableMetadataResponse{}
	mi := &file_v2_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariableMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableMetadataResponse) ProtoMessage() {}

func (x *GetVariableMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetVariableMetadataResponse) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{9}
}

func (x *GetVariableMetadataResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetVariableMetadataResponse) GetVariables() map[string]*GetVariableMetadataResponse_VariableMetadata {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *GetVariableMetadataResponse) GetProvenances() map[string]*GetVariableMetadataResponse_ProvenanceMetadata {
	if x != nil {
		return x.Provenances
	}
	return nil
}

// Request payload for the inspect_indicator_nodes tool endpoint.
type InspectIndicatorNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dcids         []string               `protobuf:"bytes,1,rep,name=dcids,proto3" json:"dcids,omitempty"`
	PlaceDcids    []string               `protobuf:"bytes,2,rep,name=place_dcids,json=placeDcids,proto3" json:"place_dcids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectIndicatorNodesRequest) Reset() {
	*x = InspectIndicatorNodesRequest{}
	mi := &file_v2_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectIndicatorNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectIndicatorNodesRequest) ProtoMessage() {}

func (x *InspectIndicatorNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectIndicatorNodesRequest.ProtoReflect.Descriptor instead.
func (*InspectIndicatorNodesRequest) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{10}
}

func (x *InspectIndicatorNodesRequest) GetDcids() []string {
	if x != nil {
		return x.Dcids
	}
	return nil
}

func (x *InspectIndicatorNodesRequest) GetPlaceDcids() []string {
	if x != nil {
		return x.PlaceDcids
	}
	return nil
}

// Response payload for the inspect_indicator_nodes tool endpoint.
type InspectIndicatorNodesResponse struct {
	state         protoimpl.MessageState                             `protogen:"open.v1"`
	Topics        []*InspectIndicatorNodesResponse_TopicInspection   `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	StatVars      []*InspectIndicatorNodesResponse_StatVarInspection `protobuf:"bytes,2,rep,name=stat_vars,json=statVars,proto3" json:"stat_vars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectIndicatorNodesResponse) Reset() {
	*x = InspectIndicatorNodesResponse{}
	mi := &file_v2_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectIndicatorNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectIndicatorNodesResponse) ProtoMessage() {}

func (x *InspectIndicatorNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectIndicatorNodesResponse.ProtoReflect.Descriptor instead.
func (*InspectIndicatorNodesResponse) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{11}
}

func (x *InspectIndicatorNodesResponse) GetTopics() []*InspectIndicatorNodesResponse_TopicInspection {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *InspectIndicatorNodesResponse) GetStatVars() []*InspectIndicatorNodesResponse_StatVarInspection {
	if x != nil {
		return x.StatVars
	}
	return nil
}

type SearchIndicatorsResponse_Topic struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Dcid                  string                 `protobuf:"bytes,1,opt,name=dcid,proto3" json:"dcid,omitempty"`
	MemberTopics          []string               `protobuf:"bytes,2,rep,name=member_topics,json=memberTopics,proto3" json:"member_topics,omitempty"`
	MemberVariables       []string               `protobuf:"bytes,3,rep,name=member_variables,json=memberVariables,proto3" json:"member_variables,omitempty"`
	PlacesWithData        []string               `protobuf:"bytes,4,rep,name=places_with_data,json=placesWithData,proto3" json:"places_with_data,omitempty"`
	Description           string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	AlternateDescriptions []string               `protobuf:"bytes,6,rep,name=alternate_descriptions,json=alternateDescriptions,proto3" json:"alternate_descriptions,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SearchIndicatorsResponse_Topic) Reset() {
	*x = SearchIndicatorsResponse_Topic{}
	mi := &file_v2_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchIndicatorsResponse_Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchIndicatorsResponse_Topic) ProtoMessage() {}

func (x *SearchIndicatorsResponse_Topic) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchIndicatorsResponse_Topic.ProtoReflect.Descriptor instead.
func (*SearchIndicatorsResponse_Topic) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{3, 0}
}

func (x *SearchIndicatorsResponse_Topic) GetDcid() string {
	if x != nil {
		return x.Dcid
	}
	return ""
}

func (x *SearchIndicatorsResponse_Topic) GetMemberTopics() []string {
	if x != nil {
		return x.MemberTopics
	}
	return nil
}

func (x *SearchIndicatorsResponse_Topic) GetMemberVariables() []string {
	if x != nil {
		return x.MemberVariables
	}
	return nil
}

func (x *SearchIndicatorsResponse_Topic) GetPlacesWithData() []string {
	if x != nil {
		return x.PlacesWithData
	}
	return nil
}

func (x *SearchIndicatorsResponse_Topic) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SearchIndicatorsResponse_Topic) GetAlternateDescriptions() []string {
	if x != nil {
		return x.AlternateDescriptions
	}
	return nil
}

type SearchIndicatorsResponse_Variable struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Dcid                  string                 `protobuf:"bytes,1,opt,name=dcid,proto3" json:"dcid,omitempty"`
	PlacesWithData        []string               `protobuf:"bytes,2,rep,name=places_with_data,json=placesWithData,proto3" json:"places_with_data,omitempty"`
	Description           string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AlternateDescriptions []string               `protobuf:"bytes,4,rep,name=alternate_descriptions,json=alternateDescriptions,proto3" json:"alternate_descriptions,omitempty"`
	ObservationProperties []string               `protobuf:"bytes,5,rep,name=observation_properties,json=observationProperties,proto3" json:"observation_properties,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SearchIndicatorsResponse_Variable) Reset() {
	*x = SearchIndicatorsResponse_Variable{}
	mi := &file_v2_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchIndicatorsResponse_Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchIndicatorsResponse_Variable) ProtoMessage() {}

func (x *SearchIndicatorsResponse_Variable) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchIndicatorsResponse_Variable.ProtoReflect.Descriptor instead.
func (*SearchIndicatorsResponse_Variable) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{3, 1}
}

func (x *SearchIndicatorsResponse_Variable) GetDcid() string {
	if x != nil {
		return x.Dcid
	}
	return ""
}

func (x *SearchIndicatorsResponse_Variable) GetPlacesWithData() []string {
	if x != nil {
		return x.PlacesWithData
	}
	return nil
}

func (x *SearchIndicatorsResponse_Variable) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SearchIndicatorsResponse_Variable) GetAlternateDescriptions() []string {
	if x != nil {
		return x.AlternateDescriptions
	}
	return nil
}

func (x *SearchIndicatorsResponse_Variable) GetObservationProperties() []string {
	if x != nil {
		return x.ObservationProperties
	}
	return nil
}

type SearchIndicatorsResponse_ResolvedPlace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dcid          string                 `protobuf:"bytes,1,opt,name=dcid,proto3" json:"dcid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TypeOf        []string               `protobuf:"bytes,3,rep,name=type_of,json=typeOf,proto3" json:"type_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchIndicatorsResponse_ResolvedPlace) Reset() {
	*x = SearchIndicatorsResponse_ResolvedPlace{}
	mi := &file_v2_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchIndicatorsResponse_ResolvedPlace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchIndicatorsResponse_ResolvedPlace) ProtoMessage() {}

func (x *SearchIndicatorsResponse_ResolvedPlace) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchIndicatorsResponse_ResolvedPlace.ProtoReflect.Descriptor instead.
func (*SearchIndicatorsResponse_ResolvedPlace) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{3, 2}
}

func (x *SearchIndicatorsResponse_ResolvedPlace) GetDcid() string {
	if x != nil {
		return x.Dcid
	}
	return ""
}

func (x *SearchIndicatorsResponse_ResolvedPlace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchIndicatorsResponse_ResolvedPlace) GetTypeOf() []string {
	if x != nil {
		return x.TypeOf
	}
	return nil
}

type GetObservationsResponse_Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dcid          string                 `protobuf:"bytes,1,opt,name=dcid,proto3" json:"dcid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TypeOf        []string               `protobuf:"bytes,3,rep,name=type_of,json=typeOf,proto3" json:"type_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObservationsResponse_Node) Reset() {
	*x = GetObservationsResponse_Node{}
	mi := &file_v2_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObservationsResponse_Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObservationsResponse_Node) ProtoMessage() {}

func (x *GetObservationsResponse_Node) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObservationsResponse_Node.ProtoReflect.Descriptor instead.
func (*GetObservationsResponse_Node) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetObservationsResponse_Node) GetDcid() string {
	if x != nil {
		return x.Dcid
	}
	return ""
}

func (x *GetObservationsResponse_Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetObservationsResponse_Node) GetTypeOf() []string {
	if x != nil {
		return x.TypeOf
	}
	return nil
}

type GetObservationsResponse_FacetMetadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SourceId          string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	ImportName        string                 `protobuf:"bytes,2,opt,name=import_name,json=importName,proto3" json:"import_name,omitempty"`
	MeasurementMethod string                 `protobuf:"bytes,3,opt,name=measurement_method,json=measurementMethod,proto3" json:"measurement_method,omitempty"`
	ObservationPeriod string                 `protobuf:"bytes,4,opt,name=observation_period,json=observationPeriod,proto3" json:"observation_period,omitempty"`
	ProvenanceUrl     string                 `protobuf:"bytes,5,opt,name=provenance_url,json=provenanceUrl,proto3" json:"provenance_url,omitempty"`
	Unit              string                 `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetObservationsResponse_FacetMetadata) Reset() {
	*x = GetObservationsResponse_FacetMetadata{}
	mi := &file_v2_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObservationsResponse_FacetMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObservationsResponse_FacetMetadata) ProtoMessage() {}

func (x *GetObservationsResponse_FacetMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObservationsResponse_FacetMetadata.ProtoReflect.Descriptor instead.
func (*GetObservationsResponse_FacetMetadata) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{7, 1}
}

func (x *GetObservationsResponse_FacetMetadata) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *GetObservationsResponse_FacetMetadata) GetImportName() string {
	if x != nil {
		return x.ImportName
	}
	return ""
}

func (x *GetObservationsResponse_FacetMetadata) GetMeasurementMethod() string {
	if x != nil {
		return x.MeasurementMethod
	}
	return ""
}

func (x *GetObservationsResponse_FacetMetadata) GetObservationPeriod() string {
	if x != nil {
		return x.ObservationPeriod
	}
	return ""
}

func (x *GetObservationsResponse_FacetMetadata) GetProvenanceUrl() string {
	if x != nil {
		return x.ProvenanceUrl
	}
	return ""
}

func (x *GetObservationsResponse_FacetMetadata) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type GetObservationsResponse_AlternativeSource struct {
	state            protoimpl.MessageState                 `protogen:"open.v1"`
	SourceMetadata   *GetObservationsResponse_FacetMetadata `protobuf:"bytes,1,opt,name=source_metadata,json=sourceMetadata,proto3" json:"source_metadata,omitempty"`
	PlacesFoundCount *int32                                 `protobuf:"varint,2,opt,name=places_found_count,json=placesFoundCount,proto3,oneof" json:"places_found_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetObservationsResponse_AlternativeSource) Reset() {
	*x = GetObservationsResponse_AlternativeSource{}
	mi := &file_v2_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObservationsResponse_AlternativeSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObservationsResponse_AlternativeSource) ProtoMessage() {}

func (x *GetObservationsResponse_AlternativeSource) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObservationsResponse_AlternativeSource.ProtoReflect.Descriptor instead.
func (*GetObservationsResponse_AlternativeSource) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{7, 2}
}

func (x *GetObservationsResponse_AlternativeSource) GetSourceMetadata() *GetObservationsResponse_FacetMetadata {
	if x != nil {
		return x.SourceMetadata
	}
	return nil
}

func (x *GetObservationsResponse_AlternativeSource) GetPlacesFoundCount() int32 {
	if x != nil && x.PlacesFoundCount != nil {
		return *x.PlacesFoundCount
	}
	return 0
}

type GetObservationsResponse_TimeSeriesPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObservationsResponse_TimeSeriesPoint) Reset() {
	*x = GetObservationsResponse_TimeSeriesPoint{}
	mi := &file_v2_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObservationsResponse_TimeSeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObservationsResponse_TimeSeriesPoint) ProtoMessage() {}

func (x *GetObservationsResponse_TimeSeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObservationsResponse_TimeSeriesPoint.ProtoReflect.Descriptor instead.
func (*GetObservationsResponse_TimeSeriesPoint) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{7, 3}
}

func (x *GetObservationsResponse_TimeSeriesPoint) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetObservationsResponse_TimeSeriesPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetObservationsResponse_PlaceObservation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in v2/agent.proto.
	Place         *GetObservationsResponse_Node              `protobuf:"bytes,1,opt,name=place,proto3" json:"place,omitempty"`
	TimeSeries    []*GetObservationsResponse_TimeSeriesPoint `protobuf:"bytes,2,rep,name=time_series,json=timeSeries,proto3" json:"time_series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObservationsResponse_PlaceObservation) Reset() {
	*x = GetObservationsResponse_PlaceObservation{}
	mi := &file_v2_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObservationsResponse_PlaceObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObservationsResponse_PlaceObservation) ProtoMessage() {}

func (x *GetObservationsResponse_PlaceObservation) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObservationsResponse_PlaceObservation.ProtoReflect.Descriptor instead.
func (*GetObservationsResponse_PlaceObservation) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{7, 4}
}

// Deprecated: Marked as deprecated in v2/agent.proto.
func (x *GetObservationsResponse_PlaceObservation) GetPlace() *GetObservationsResponse_Node {
	if x != nil {
		return x.Place
	}
	return nil
}

func (x *GetObservationsResponse_PlaceObservation) GetTimeSeries() []*GetObservationsResponse_TimeSeriesPoint {
	if x != nil {
		return x.TimeSeries
	}
	return nil
}

type GetVariableMetadataResponse_FacetMetadata struct {
	state         protoimpl.MessageState                               `protogen:"open.v1"`
	Id            string                                               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProvenanceId  string                                               `protobuf:"bytes,2,opt,name=provenance_id,json=provenanceId,proto3" json:"provenance_id,omitempty"`
	ObsCount      int32                                                `protobuf:"varint,3,opt,name=obs_count,json=obsCount,proto3" json:"obs_count,omitempty"`
	DateRange     *GetVariableMetadataResponse_FacetMetadata_DateRange `protobuf:"bytes,4,opt,name=date_range,json=dateRange,proto3" json:"date_range,omitempty"`
	Scope         *GetVariableMetadataResponse_FacetMetadata_Scope     `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	Properties    *structpb.Struct                                     `protobuf:"bytes,6,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVariableMetadataResponse_FacetMetadata) Reset() {
	*x = GetVariableMetadataResponse_FacetMetadata{}
	mi := &file_v2_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariableMetadataResponse_FacetMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableMetadataResponse_FacetMetadata) ProtoMessage() {}

func (x *GetVariableMetadataResponse_FacetMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableMetadataResponse_FacetMetadata.ProtoReflect.Descriptor instead.
func (*GetVariableMetadataResponse_FacetMetadata) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{9, 0}
}

func (x *GetVariableMetadataResponse_FacetMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetVariableMetadataResponse_FacetMetadata) GetProvenanceId() string {
	if x != nil {
		return x.ProvenanceId
	}
	return ""
}

func (x *GetVariableMetadataResponse_FacetMetadata) GetObsCount() int32 {
	if x != nil {
		return x.ObsCount
	}
	return 0
}

func (x *GetVariableMetadataResponse_FacetMetadata) GetDateRange() *GetVariableMetadataResponse_FacetMetadata_DateRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

func (x *GetVariableMetadataResponse_FacetMetadata) GetScope() *GetVariableMetadataResponse_FacetMetadata_Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *GetVariableMetadataResponse_FacetMetadata) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

type GetVariableMetadataResponse_VariableMetadata struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Id            string                                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                                       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                                       `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Properties    *structpb.Struct                             `protobuf:"bytes,4,opt,name=properties,proto3" json:"properties,omitempty"`
	Facets        []*GetVariableMetadataResponse_FacetMetadata `protobuf:"bytes,5,rep,name=facets,proto3" json:"facets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVariableMetadataResponse_VariableMetadata) Reset() {
	*x = GetVariableMetadataResponse_VariableMetadata{}
	mi := &file_v2_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariableMetadataResponse_VariableMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableMetadataResponse_VariableMetadata) ProtoMessage() {}

func (x *GetVariableMetadataResponse_VariableMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableMetadataResponse_VariableMetadata.ProtoReflect.Descriptor instead.
func (*GetVariableMetadataResponse_VariableMetadata) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{9, 1}
}

func (x *GetVariableMetadataResponse_VariableMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetVariableMetadataResponse_VariableMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetVariableMetadataResponse_VariableMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetVariableMetadataResponse_VariableMetadata) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *GetVariableMetadataResponse_VariableMetadata) GetFacets() []*GetVariableMetadataResponse_FacetMetadata {
	if x != nil {
		return x.Facets
	}
	return nil
}

type GetVariableMetadataResponse_ProvenanceMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVariableMetadataResponse_ProvenanceMetadata) Reset() {
	*x = GetVariableMetadataResponse_ProvenanceMetadata{}
	mi := &file_v2_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariableMetadataResponse_ProvenanceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableMetadataResponse_ProvenanceMetadata) ProtoMessage() {}

func (x *GetVariableMetadataResponse_ProvenanceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableMetadataResponse_ProvenanceMetadata.ProtoReflect.Descriptor instead.
func (*GetVariableMetadataResponse_ProvenanceMetadata) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{9, 2}
}

func (x *GetVariableMetadataResponse_ProvenanceMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetVariableMetadataResponse_ProvenanceMetadata) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

type GetVariableMetadataResponse_FacetMetadata_DateRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVariableMetadataResponse_FacetMetadata_DateRange) Reset() {
	*x = GetVariableMetadataResponse_FacetMetadata_DateRange{}
	mi := &file_v2_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariableMetadataResponse_FacetMetadata_DateRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableMetadataResponse_FacetMetadata_DateRange) ProtoMessage() {}

func (x *GetVariableMetadataResponse_FacetMetadata_DateRange) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableMetadataResponse_FacetMetadata_DateRange.ProtoReflect.Descriptor instead.
func (*GetVariableMetadataResponse_FacetMetadata_DateRange) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{9, 0, 0}
}

func (x *GetVariableMetadataResponse_FacetMetadata_DateRange) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *GetVariableMetadataResponse_FacetMetadata_DateRange) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

type GetVariableMetadataResponse_FacetMetadata_Scope struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EntityCoverage    []string               `protobuf:"bytes,1,rep,name=entity_coverage,json=entityCoverage,proto3" json:"entity_coverage,omitempty"`
	EntityGranularity []string               `protobuf:"bytes,2,rep,name=entity_granularity,json=entityGranularity,proto3" json:"entity_granularity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetVariableMetadataResponse_FacetMetadata_Scope) Reset() {
	*x = GetVariableMetadataResponse_FacetMetadata_Scope{}
	mi := &file_v2_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariableMetadataResponse_FacetMetadata_Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableMetadataResponse_FacetMetadata_Scope) ProtoMessage() {}

func (x *GetVariableMetadataResponse_FacetMetadata_Scope) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableMetadataResponse_FacetMetadata_Scope.ProtoReflect.Descriptor instead.
func (*GetVariableMetadataResponse_FacetMetadata_Scope) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{9, 0, 1}
}

func (x *GetVariableMetadataResponse_FacetMetadata_Scope) GetEntityCoverage() []string {
	if x != nil {
		return x.EntityCoverage
	}
	return nil
}

func (x *GetVariableMetadataResponse_FacetMetadata_Scope) GetEntityGranularity() []string {
	if x != nil {
		return x.EntityGranularity
	}
	return nil
}

type InspectIndicatorNodesResponse_DimensionSliceSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Dimension      string                 `protobuf:"bytes,1,opt,name=dimension,proto3" json:"dimension,omitempty"`
	AvailableCount int32                  `protobuf:"varint,2,opt,name=available_count,json=availableCount,proto3" json:"available_count,omitempty"`
	SampleSlices   []string               `protobuf:"bytes,3,rep,name=sample_slices,json=sampleSlices,proto3" json:"sample_slices,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InspectIndicatorNodesResponse_DimensionSliceSummary) Reset() {
	*x = InspectIndicatorNodesResponse_DimensionSliceSummary{}
	mi := &file_v2_agent_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectIndicatorNodesResponse_DimensionSliceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectIndicatorNodesResponse_DimensionSliceSummary) ProtoMessage() {}

func (x *InspectIndicatorNodesResponse_DimensionSliceSummary) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectIndicatorNodesResponse_DimensionSliceSummary.ProtoReflect.Descriptor instead.
func (*InspectIndicatorNodesResponse_DimensionSliceSummary) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{11, 0}
}

func (x *InspectIndicatorNodesResponse_DimensionSliceSummary) GetDimension() string {
	if x != nil {
		return x.Dimension
	}
	return ""
}

func (x *InspectIndicatorNodesResponse_DimensionSliceSummary) GetAvailableCount() int32 {
	if x != nil {
		return x.AvailableCount
	}
	return 0
}

func (x *InspectIndicatorNodesResponse_DimensionSliceSummary) GetSampleSlices() []string {
	if x != nil {
		return x.SampleSlices
	}
	return nil
}

type InspectIndicatorNodesResponse_StatVarInspection struct {
	state         protoimpl.MessageState                                 `protogen:"open.v1"`
	SeedDcid      string                                                 `protobuf:"bytes,1,opt,name=seed_dcid,json=seedDcid,proto3" json:"seed_dcid,omitempty"`
	Name          string                                                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Provenances   []string                                               `protobuf:"bytes,3,rep,name=provenances,proto3" json:"provenances,omitempty"`
	EarliestDate  string                                                 `protobuf:"bytes,4,opt,name=earliest_date,json=earliestDate,proto3" json:"earliest_date,omitempty"`
	LatestDate    string                                                 `protobuf:"bytes,5,opt,name=latest_date,json=latestDate,proto3" json:"latest_date,omitempty"`
	RootSvg       string                                                 `protobuf:"bytes,6,opt,name=root_svg,json=rootSvg,proto3" json:"root_svg,omitempty"`
	Dimensions    []*InspectIndicatorNodesResponse_DimensionSliceSummary `protobuf:"bytes,7,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectIndicatorNodesResponse_StatVarInspection) Reset() {
	*x = InspectIndicatorNodesResponse_StatVarInspection{}
	mi := &file_v2_agent_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectIndicatorNodesResponse_StatVarInspection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectIndicatorNodesResponse_StatVarInspection) ProtoMessage() {}

func (x *InspectIndicatorNodesResponse_StatVarInspection) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectIndicatorNodesResponse_StatVarInspection.ProtoReflect.Descriptor instead.
func (*InspectIndicatorNodesResponse_StatVarInspection) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{11, 1}
}

func (x *InspectIndicatorNodesResponse_StatVarInspection) GetSeedDcid() string {
	if x != nil {
		return x.SeedDcid
	}
	return ""
}

func (x *InspectIndicatorNodesResponse_StatVarInspection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InspectIndicatorNodesResponse_StatVarInspection) GetProvenances() []string {
	if x != nil {
		return x.Provenances
	}
	return nil
}

func (x *InspectIndicatorNodesResponse_StatVarInspection) GetEarliestDate() string {
	if x != nil {
		return x.EarliestDate
	}
	return ""
}

func (x *InspectIndicatorNodesResponse_StatVarInspection) GetLatestDate() string {
	if x != nil {
		return x.LatestDate
	}
	return ""
}

func (x *InspectIndicatorNodesResponse_StatVarInspection) GetRootSvg() string {
	if x != nil {
		return x.RootSvg
	}
	return ""
}

func (x *InspectIndicatorNodesResponse_StatVarInspection) GetDimensions() []*InspectIndicatorNodesResponse_DimensionSliceSummary {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

type InspectIndicatorNodesResponse_TopicInspection struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TopicDcid         string                 `protobuf:"bytes,1,opt,name=topic_dcid,json=topicDcid,proto3" json:"topic_dcid,omitempty"`
	HeadlineVariables []string               `protobuf:"bytes,2,rep,name=headline_variables,json=headlineVariables,proto3" json:"headline_variables,omitempty"`
	ChildTopics       []string               `protobuf:"bytes,3,rep,name=child_topics,json=childTopics,proto3" json:"child_topics,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InspectIndicatorNodesResponse_TopicInspection) Reset() {
	*x = InspectIndicatorNodesResponse_TopicInspection{}
	mi := &file_v2_agent_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectIndicatorNodesResponse_TopicInspection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectIndicatorNodesResponse_TopicInspection) ProtoMessage() {}

func (x *InspectIndicatorNodesResponse_TopicInspection) ProtoReflect() protoreflect.Message {
	mi := &file_v2_agent_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectIndicatorNodesResponse_TopicInspection.ProtoReflect.Descriptor instead.
func (*InspectIndicatorNodesResponse_TopicInspection) Descriptor() ([]byte, []int) {
	return file_v2_agent_proto_rawDescGZIP(), []int{11, 2}
}

func (x *InspectIndicatorNodesResponse_TopicInspection) GetTopicDcid() string {
	if x != nil {
		return x.TopicDcid
	}
	return ""
}

func (x *InspectIndicatorNodesResponse_TopicInspection) GetHeadlineVariables() []string {
	if x != nil {
		return x.HeadlineVariables
	}
	return nil
}

func (x *InspectIndicatorNodesResponse_TopicInspection) GetChildTopics() []string {
	if x != nil {
		return x.ChildTopics
	}
	return nil
}

var File_v2_agent_proto protoreflect.FileDescriptor

const file_v2_agent_proto_rawDesc = "" +
	"\n" +
	"\x0ev2/agent.proto\x12\x0edatacommons.v2\x1a\x1cgoogle/protobuf/struct.proto\"V\n" +
	"\x14ResolvePlacesRequest\x12\x16\n" +
	"\x06places\x18\x01 \x03(\tR\x06places\x12\x1b\n" +
	"\x06target\x18\x02 \x01(\tH\x00R\x06target\x88\x01\x01B\t\n" +
	"\a_target\"o\n" +
	"\x15ResolvePlacesResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12>\n" +
	"\x0fresolved_places\x18\x02 \x01(\v2\x15.datacommons.v2.TableR\x0eresolvedPlaces\"\xe0\x02\n" +
	"\x17SearchIndicatorsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1a\n" +
	"\x06places\x18\x02 \x03(\tB\x02\x18\x01R\x06places\x12%\n" +
	"\fparent_place\x18\x03 \x01(\tB\x02\x18\x01R\vparentPlace\x12(\n" +
	"\x10per_search_limit\x18\x04 \x01(\x05R\x0eperSearchLimit\x12*\n" +
	"\x0einclude_topics\x18\x05 \x01(\bH\x00R\rincludeTopics\x88\x01\x01\x12(\n" +
	"\rexpand_topics\x18\x06 \x01(\bH\x01R\fexpandTopics\x88\x01\x01\x12\x1b\n" +
	"\x06target\x18\a \x01(\tH\x02R\x06target\x88\x01\x01\x12\x1f\n" +
	"\vplace_dcids\x18\b \x03(\tR\n" +
	"placeDcidsB\x11\n" +
	"\x0f_include_topicsB\x10\n" +
	"\x0e_expand_topicsB\t\n" +
	"\a_target\"\x8b\v\n" +
	"\x18SearchIndicatorsResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12p\n" +
	"\x12dcid_name_mappings\x18\x02 \x03(\v2>.datacommons.v2.SearchIndicatorsResponse.DcidNameMappingsEntryB\x02\x18\x01R\x10dcidNameMappings\x12\x80\x01\n" +
	"\x18dcid_place_type_mappings\x18\x03 \x03(\v2C.datacommons.v2.SearchIndicatorsResponse.DcidPlaceTypeMappingsEntryB\x02\x18\x01R\x15dcidPlaceTypeMappings\x12J\n" +
	"\x06topics\x18\x04 \x03(\v2..datacommons.v2.SearchIndicatorsResponse.TopicB\x02\x18\x01R\x06topics\x12S\n" +
	"\tvariables\x18\x05 \x03(\v21.datacommons.v2.SearchIndicatorsResponse.VariableB\x02\x18\x01R\tvariables\x12n\n" +
	"\x15resolved_parent_place\x18\x06 \x01(\v26.datacommons.v2.SearchIndicatorsResponse.ResolvedPlaceB\x02\x18\x01R\x13resolvedParentPlace\x12@\n" +
	"\x10topic_candidates\x18\a \x01(\v2\x15.datacommons.v2.TableR\x0ftopicCandidates\x12F\n" +
	"\x13variable_candidates\x18\b \x01(\v2\x15.datacommons.v2.TableR\x12variableCandidates\x1a\xee\x01\n" +
	"\x05Topic\x12\x12\n" +
	"\x04dcid\x18\x01 \x01(\tR\x04dcid\x12#\n" +
	"\rmember_topics\x18\x02 \x03(\tR\fmemberTopics\x12)\n" +
	"\x10member_variables\x18\x03 \x03(\tR\x0fmemberVariables\x12(\n" +
	"\x10places_with_data\x18\x04 \x03(\tR\x0eplacesWithData\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x125\n" +
	"\x16alternate_descriptions\x18\x06 \x03(\tR\x15alternateDescriptions\x1a\xd8\x01\n" +
	"\bVariable\x12\x12\n" +
	"\x04dcid\x18\x01 \x01(\tR\x04dcid\x12(\n" +
	"\x10places_with_data\x18\x02 \x03(\tR\x0eplacesWithData\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x125\n" +
	"\x16alternate_descriptions\x18\x04 \x03(\tR\x15alternateDescriptions\x125\n" +
	"\x16observation_properties\x18\x05 \x03(\tR\x15observationProperties\x1aP\n" +
	"\rResolvedPlace\x12\x12\n" +
	"\x04dcid\x18\x01 \x01(\tR\x04dcid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\atype_of\x18\x03 \x03(\tR\x06typeOf\x1aC\n" +
	"\x15DcidNameMappingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1ad\n" +
	"\x1aDcidPlaceTypeMappingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.ListValueR\x05value:\x028\x01\"\"\n" +
	"\n" +
	"EntityList\x12\x14\n" +
	"\x05dcids\x18\x01 \x03(\tR\x05dcids\"Q\n" +
	"\x05Table\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12.\n" +
	"\x04rows\x18\x02 \x03(\v2\x1a.google.protobuf.ListValueR\x04rows\"\xb5\x04\n" +
	"\x16GetObservationsRequest\x12#\n" +
	"\rvariable_dcid\x18\x01 \x01(\tR\fvariableDcid\x12!\n" +
	"\n" +
	"place_dcid\x18\x02 \x01(\tB\x02\x18\x01R\tplaceDcid\x121\n" +
	"\x10child_place_type\x18\x03 \x01(\tB\x02\x18\x01H\x00R\x0echildPlaceType\x88\x01\x01\x12,\n" +
	"\x0fsource_override\x18\x04 \x01(\tH\x01R\x0esourceOverride\x88\x01\x01\x12\x17\n" +
	"\x04date\x18\x05 \x01(\tH\x02R\x04date\x88\x01\x01\x12-\n" +
	"\x10date_range_start\x18\x06 \x01(\tH\x03R\x0edateRangeStart\x88\x01\x01\x12)\n" +
	"\x0edate_range_end\x18\a \x01(\tH\x04R\fdateRangeEnd\x88\x01\x01\x12P\n" +
	"\bentities\x18\b \x03(\v24.datacommons.v2.GetObservationsRequest.EntitiesEntryR\bentities\x1aS\n" +
	"\rEntitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01B\x13\n" +
	"\x11_child_place_typeB\x12\n" +
	"\x10_source_overrideB\a\n" +
	"\x05_dateB\x13\n" +
	"\x11_date_range_startB\x11\n" +
	"\x0f_date_range_end\"\x81\v\n" +
	"\x17GetObservationsResponse\x12H\n" +
	"\bvariable\x18\x01 \x01(\v2,.datacommons.v2.GetObservationsResponse.NodeR\bvariable\x12d\n" +
	"\x15resolved_parent_place\x18\x02 \x01(\v2,.datacommons.v2.GetObservationsResponse.NodeB\x02\x18\x01R\x13resolvedParentPlace\x12,\n" +
	"\x10child_place_type\x18\x03 \x01(\tB\x02\x18\x01R\x0echildPlaceType\x12>\n" +
	"\x0fentity_metadata\x18\a \x01(\v2\x15.datacommons.v2.TableR\x0eentityMetadata\x12)\n" +
	"\x04data\x18\b \x01(\v2\x15.datacommons.v2.TableR\x04data\x12k\n" +
	"\x12place_observations\x18\x04 \x03(\v28.datacommons.v2.GetObservationsResponse.PlaceObservationB\x02\x18\x01R\x11placeObservations\x12^\n" +
	"\x0fsource_metadata\x18\x05 \x01(\v25.datacommons.v2.GetObservationsResponse.FacetMetadataR\x0esourceMetadata\x12j\n" +
	"\x13alternative_sources\x18\x06 \x03(\v29.datacommons.v2.GetObservationsResponse.AlternativeSourceR\x12alternativeSources\x1aG\n" +
	"\x04Node\x12\x12\n" +
	"\x04dcid\x18\x01 \x01(\tR\x04dcid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\atype_of\x18\x03 \x03(\tR\x06typeOf\x1a\xe6\x01\n" +
	"\rFacetMetadata\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1f\n" +
	"\vimport_name\x18\x02 \x01(\tR\n" +
	"importName\x12-\n" +
	"\x12measurement_method\x18\x03 \x01(\tR\x11measurementMethod\x12-\n" +
	"\x12observation_period\x18\x04 \x01(\tR\x11observationPeriod\x12%\n" +
	"\x0eprovenance_url\x18\x05 \x01(\tR\rprovenanceUrl\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x1a\xbd\x01\n" +
	"\x11AlternativeSource\x12^\n" +
	"\x0fsource_metadata\x18\x01 \x01(\v25.datacommons.v2.GetObservationsResponse.FacetMetadataR\x0esourceMetadata\x121\n" +
	"\x12places_found_count\x18\x02 \x01(\x05H\x00R\x10placesFoundCount\x88\x01\x01B\x15\n" +
	"\x13_places_found_count\x1a;\n" +
	"\x0fTimeSeriesPoint\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x1a\xb4\x01\n" +
	"\x10PlaceObservation\x12F\n" +
	"\x05place\x18\x01 \x01(\v2,.datacommons.v2.GetObservationsResponse.NodeB\x02\x18\x01R\x05place\x12X\n" +
	"\vtime_series\x18\x02 \x03(\v27.datacommons.v2.GetObservationsResponse.TimeSeriesPointR\n" +
	"timeSeries\"f\n" +
	"\x1aGetVariableMetadataRequest\x12%\n" +
	"\x0evariable_dcids\x18\x01 \x03(\tR\rvariableDcids\x12!\n" +
	"\fentity_dcids\x18\x02 \x03(\tR\ventityDcids\"\x9f\n" +
	"\n" +
	"\x1bGetVariableMetadataResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12X\n" +
	"\tvariables\x18\x02 \x03(\v2:.datacommons.v2.GetVariableMetadataResponse.VariablesEntryR\tvariables\x12^\n" +
	"\vprovenances\x18\x03 \x03(\v2<.datacommons.v2.GetVariableMetadataResponse.ProvenancesEntryR\vprovenances\x1a\xeb\x03\n" +
	"\rFacetMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rprovenance_id\x18\x02 \x01(\tR\fprovenanceId\x12\x1b\n" +
	"\tobs_count\x18\x03 \x01(\x05R\bobsCount\x12b\n" +
	"\n" +
	"date_range\x18\x04 \x01(\v2C.datacommons.v2.GetVariableMetadataResponse.FacetMetadata.DateRangeR\tdateRange\x12U\n" +
	"\x05scope\x18\x05 \x01(\v2?.datacommons.v2.GetVariableMetadataResponse.FacetMetadata.ScopeR\x05scope\x127\n" +
	"\n" +
	"properties\x18\x06 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\x1a3\n" +
	"\tDateRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\x1a_\n" +
	"\x05Scope\x12'\n" +
	"\x0fentity_coverage\x18\x01 \x03(\tR\x0eentityCoverage\x12-\n" +
	"\x12entity_granularity\x18\x02 \x03(\tR\x11entityGranularity\x1a\xe4\x01\n" +
	"\x10VariableMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x127\n" +
	"\n" +
	"properties\x18\x04 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\x12Q\n" +
	"\x06facets\x18\x05 \x03(\v29.datacommons.v2.GetVariableMetadataResponse.FacetMetadataR\x06facets\x1a]\n" +
	"\x12ProvenanceMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\n" +
	"properties\x18\x02 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\x1az\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12R\n" +
	"\x05value\x18\x02 \x01(\v2<.datacommons.v2.GetVariableMetadataResponse.VariableMetadataR\x05value:\x028\x01\x1a~\n" +
	"\x10ProvenancesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12T\n" +
	"\x05value\x18\x02 \x01(\v2>.datacommons.v2.GetVariableMetadataResponse.ProvenanceMetadataR\x05value:\x028\x01\"U\n" +
	"\x1cInspectIndicatorNodesRequest\x12\x14\n" +
	"\x05dcids\x18\x01 \x03(\tR\x05dcids\x12\x1f\n" +
	"\vplace_dcids\x18\x02 \x03(\tR\n" +
	"placeDcids\"\x8e\x06\n" +
	"\x1dInspectIndicatorNodesResponse\x12U\n" +
	"\x06topics\x18\x01 \x03(\v2=.datacommons.v2.InspectIndicatorNodesResponse.TopicInspectionR\x06topics\x12\\\n" +
	"\tstat_vars\x18\x02 \x03(\v2?.datacommons.v2.InspectIndicatorNodesResponse.StatVarInspectionR\bstatVars\x1a\x83\x01\n" +
	"\x15DimensionSliceSummary\x12\x1c\n" +
	"\tdimension\x18\x01 \x01(\tR\tdimension\x12'\n" +
	"\x0favailable_count\x18\x02 \x01(\x05R\x0eavailableCount\x12#\n" +
	"\rsample_slices\x18\x03 \x03(\tR\fsampleSlices\x1a\xac\x02\n" +
	"\x11StatVarInspection\x12\x1b\n" +
	"\tseed_dcid\x18\x01 \x01(\tR\bseedDcid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vprovenances\x18\x03 \x03(\tR\vprovenances\x12#\n" +
	"\rearliest_date\x18\x04 \x01(\tR\fearliestDate\x12\x1f\n" +
	"\vlatest_date\x18\x05 \x01(\tR\n" +
	"latestDate\x12\x19\n" +
	"\broot_svg\x18\x06 \x01(\tR\arootSvg\x12c\n" +
	"\n" +
	"dimensions\x18\a \x03(\v2C.datacommons.v2.InspectIndicatorNodesResponse.DimensionSliceSummaryR\n" +
	"dimensions\x1a\x82\x01\n" +
	"\x0fTopicInspection\x12\x1d\n" +
	"\n" +
	"topic_dcid\x18\x01 \x01(\tR\ttopicDcid\x12-\n" +
	"\x12headline_variables\x18\x02 \x03(\tR\x11headlineVariables\x12!\n" +
	"\fchild_topics\x18\x03 \x03(\tR\vchildTopicsB3Z1github.com/datacommonsorg/mixer/internal/proto/v2b\x06proto3"

var (
	file_v2_agent_proto_rawDescOnce sync.Once
	file_v2_agent_proto_rawDescData []byte
)

func file_v2_agent_proto_rawDescGZIP() []byte {
	file_v2_agent_proto_rawDescOnce.Do(func() {
		file_v2_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_agent_proto_rawDesc), len(file_v2_agent_proto_rawDesc)))
	})
	return file_v2_agent_proto_rawDescData
}

var file_v2_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_v2_agent_proto_goTypes = []any{
	(*ResolvePlacesRequest)(nil),                   // 0: datacommons.v2.ResolvePlacesRequest
	(*ResolvePlacesResponse)(nil),                  // 1: datacommons.v2.ResolvePlacesResponse
	(*SearchIndicatorsRequest)(nil),                // 2: datacommons.v2.SearchIndicatorsRequest
	(*SearchIndicatorsResponse)(nil),               // 3: datacommons.v2.SearchIndicatorsResponse
	(*EntityList)(nil),                             // 4: datacommons.v2.EntityList
	(*Table)(nil),                                  // 5: datacommons.v2.Table
	(*GetObservationsRequest)(nil),                 // 6: datacommons.v2.GetObservationsRequest
	(*GetObservationsResponse)(nil),                // 7: datacommons.v2.GetObservationsResponse
	(*GetVariableMetadataRequest)(nil),             // 8: datacommons.v2.GetVariableMetadataRequest
	(*GetVariableMetadataResponse)(nil),            // 9: datacommons.v2.GetVariableMetadataResponse
	(*InspectIndicatorNodesRequest)(nil),           // 10: datacommons.v2.InspectIndicatorNodesRequest
	(*InspectIndicatorNodesResponse)(nil),          // 11: datacommons.v2.InspectIndicatorNodesResponse
	(*SearchIndicatorsResponse_Topic)(nil),         // 12: datacommons.v2.SearchIndicatorsResponse.Topic
	(*SearchIndicatorsResponse_Variable)(nil),      // 13: datacommons.v2.SearchIndicatorsResponse.Variable
	(*SearchIndicatorsResponse_ResolvedPlace)(nil), // 14: datacommons.v2.SearchIndicatorsResponse.ResolvedPlace
	nil,                                  // 15: datacommons.v2.SearchIndicatorsResponse.DcidNameMappingsEntry
	nil,                                  // 16: datacommons.v2.SearchIndicatorsResponse.DcidPlaceTypeMappingsEntry
	nil,                                  // 17: datacommons.v2.GetObservationsRequest.EntitiesEntry
	(*GetObservationsResponse_Node)(nil), // 18: datacommons.v2.GetObservationsResponse.Node
	(*GetObservationsResponse_FacetMetadata)(nil),          // 19: datacommons.v2.GetObservationsResponse.FacetMetadata
	(*GetObservationsResponse_AlternativeSource)(nil),      // 20: datacommons.v2.GetObservationsResponse.AlternativeSource
	(*GetObservationsResponse_TimeSeriesPoint)(nil),        // 21: datacommons.v2.GetObservationsResponse.TimeSeriesPoint
	(*GetObservationsResponse_PlaceObservation)(nil),       // 22: datacommons.v2.GetObservationsResponse.PlaceObservation
	(*GetVariableMetadataResponse_FacetMetadata)(nil),      // 23: datacommons.v2.GetVariableMetadataResponse.FacetMetadata
	(*GetVariableMetadataResponse_VariableMetadata)(nil),   // 24: datacommons.v2.GetVariableMetadataResponse.VariableMetadata
	(*GetVariableMetadataResponse_ProvenanceMetadata)(nil), // 25: datacommons.v2.GetVariableMetadataResponse.ProvenanceMetadata
	nil, // 26: datacommons.v2.GetVariableMetadataResponse.VariablesEntry
	nil, // 27: datacommons.v2.GetVariableMetadataResponse.ProvenancesEntry
	(*GetVariableMetadataResponse_FacetMetadata_DateRange)(nil), // 28: datacommons.v2.GetVariableMetadataResponse.FacetMetadata.DateRange
	(*GetVariableMetadataResponse_FacetMetadata_Scope)(nil),     // 29: datacommons.v2.GetVariableMetadataResponse.FacetMetadata.Scope
	(*InspectIndicatorNodesResponse_DimensionSliceSummary)(nil), // 30: datacommons.v2.InspectIndicatorNodesResponse.DimensionSliceSummary
	(*InspectIndicatorNodesResponse_StatVarInspection)(nil),     // 31: datacommons.v2.InspectIndicatorNodesResponse.StatVarInspection
	(*InspectIndicatorNodesResponse_TopicInspection)(nil),       // 32: datacommons.v2.InspectIndicatorNodesResponse.TopicInspection
	(*structpb.ListValue)(nil),                                  // 33: google.protobuf.ListValue
	(*structpb.Value)(nil),                                      // 34: google.protobuf.Value
	(*structpb.Struct)(nil),                                     // 35: google.protobuf.Struct
}
var file_v2_agent_proto_depIdxs = []int32{
	5,  // 0: datacommons.v2.ResolvePlacesResponse.resolved_places:type_name -> datacommons.v2.Table
	15, // 1: datacommons.v2.SearchIndicatorsResponse.dcid_name_mappings:type_name -> datacommons.v2.SearchIndicatorsResponse.DcidNameMappingsEntry
	16, // 2: datacommons.v2.SearchIndicatorsResponse.dcid_place_type_mappings:type_name -> datacommons.v2.SearchIndicatorsResponse.DcidPlaceTypeMappingsEntry
	12, // 3: datacommons.v2.SearchIndicatorsResponse.topics:type_name -> datacommons.v2.SearchIndicatorsResponse.Topic
	13, // 4: datacommons.v2.SearchIndicatorsResponse.variables:type_name -> datacommons.v2.SearchIndicatorsResponse.Variable
	14, // 5: datacommons.v2.SearchIndicatorsResponse.resolved_parent_place:type_name -> datacommons.v2.SearchIndicatorsResponse.ResolvedPlace
	5,  // 6: datacommons.v2.SearchIndicatorsResponse.topic_candidates:type_name -> datacommons.v2.Table
	5,  // 7: datacommons.v2.SearchIndicatorsResponse.variable_candidates:type_name -> datacommons.v2.Table
	33, // 8: datacommons.v2.Table.rows:type_name -> google.protobuf.ListValue
	17, // 9: datacommons.v2.GetObservationsRequest.entities:type_name -> datacommons.v2.GetObservationsRequest.EntitiesEntry
	18, // 10: datacommons.v2.GetObservationsResponse.variable:type_name -> datacommons.v2.GetObservationsResponse.Node
	18, // 11: datacommons.v2.GetObservationsResponse.resolved_parent_place:type_name -> datacommons.v2.GetObservationsResponse.Node
	5,  // 12: datacommons.v2.GetObservationsResponse.entity_metadata:type_name -> datacommons.v2.Table
	5,  // 13: datacommons.v2.GetObservationsResponse.data:type_name -> datacommons.v2.Table
	22, // 14: datacommons.v2.GetObservationsResponse.place_observations:type_name -> datacommons.v2.GetObservationsResponse.PlaceObservation
	19, // 15: datacommons.v2.GetObservationsResponse.source_metadata:type_name -> datacommons.v2.GetObservationsResponse.FacetMetadata
	20, // 16: datacommons.v2.GetObservationsResponse.alternative_sources:type_name -> datacommons.v2.GetObservationsResponse.AlternativeSource
	26, // 17: datacommons.v2.GetVariableMetadataResponse.variables:type_name -> datacommons.v2.GetVariableMetadataResponse.VariablesEntry
	27, // 18: datacommons.v2.GetVariableMetadataResponse.provenances:type_name -> datacommons.v2.GetVariableMetadataResponse.ProvenancesEntry
	32, // 19: datacommons.v2.InspectIndicatorNodesResponse.topics:type_name -> datacommons.v2.InspectIndicatorNodesResponse.TopicInspection
	31, // 20: datacommons.v2.InspectIndicatorNodesResponse.stat_vars:type_name -> datacommons.v2.InspectIndicatorNodesResponse.StatVarInspection
	33, // 21: datacommons.v2.SearchIndicatorsResponse.DcidPlaceTypeMappingsEntry.value:type_name -> google.protobuf.ListValue
	34, // 22: datacommons.v2.GetObservationsRequest.EntitiesEntry.value:type_name -> google.protobuf.Value
	19, // 23: datacommons.v2.GetObservationsResponse.AlternativeSource.source_metadata:type_name -> datacommons.v2.GetObservationsResponse.FacetMetadata
	18, // 24: datacommons.v2.GetObservationsResponse.PlaceObservation.place:type_name -> datacommons.v2.GetObservationsResponse.Node
	21, // 25: datacommons.v2.GetObservationsResponse.PlaceObservation.time_series:type_name -> datacommons.v2.GetObservationsResponse.TimeSeriesPoint
	28, // 26: datacommons.v2.GetVariableMetadataResponse.FacetMetadata.date_range:type_name -> datacommons.v2.GetVariableMetadataResponse.FacetMetadata.DateRange
	29, // 27: datacommons.v2.GetVariableMetadataResponse.FacetMetadata.scope:type_name -> datacommons.v2.GetVariableMetadataResponse.FacetMetadata.Scope
	35, // 28: datacommons.v2.GetVariableMetadataResponse.FacetMetadata.properties:type_name -> google.protobuf.Struct
	35, // 29: datacommons.v2.GetVariableMetadataResponse.VariableMetadata.properties:type_name -> google.protobuf.Struct
	23, // 30: datacommons.v2.GetVariableMetadataResponse.VariableMetadata.facets:type_name -> datacommons.v2.GetVariableMetadataResponse.FacetMetadata
	35, // 31: datacommons.v2.GetVariableMetadataResponse.ProvenanceMetadata.properties:type_name -> google.protobuf.Struct
	24, // 32: datacommons.v2.GetVariableMetadataResponse.VariablesEntry.value:type_name -> datacommons.v2.GetVariableMetadataResponse.VariableMetadata
	25, // 33: datacommons.v2.GetVariableMetadataResponse.ProvenancesEntry.value:type_name -> datacommons.v2.GetVariableMetadataResponse.ProvenanceMetadata
	30, // 34: datacommons.v2.InspectIndicatorNodesResponse.StatVarInspection.dimensions:type_name -> datacommons.v2.InspectIndicatorNodesResponse.DimensionSliceSummary
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_v2_agent_proto_init() }
func file_v2_agent_proto_init() {
	if File_v2_agent_proto != nil {
		return
	}
	file_v2_agent_proto_msgTypes[0].OneofWrappers = []any{}
	file_v2_agent_proto_msgTypes[2].OneofWrappers = []any{}
	file_v2_agent_proto_msgTypes[6].OneofWrappers = []any{}
	file_v2_agent_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_agent_proto_rawDesc), len(file_v2_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_agent_proto_goTypes,
		DependencyIndexes: file_v2_agent_proto_depIdxs,
		MessageInfos:      file_v2_agent_proto_msgTypes,
	}.Build()
	File_v2_agent_proto = out.File
	file_v2_agent_proto_goTypes = nil
	file_v2_agent_proto_depIdxs = nil
}
